import type { SimulatorHeadings } from "./types";

/** Titres H2/H3 rédigés individuellement — emploi (10 simulateurs). */
export const emploiHeadings: Record<string, SimulatorHeadings> = {
  "salaire-brut-net": {
    mainSection: "Comment passer du salaire brut au net ?",
    definition: "Quelle différence entre salaire brut et salaire net ?",
    objectif: "Pourquoi estimer son net avant de recevoir la fiche de paie ?",
    variables: "Quel salaire brut, statut et taux de cotisations renseigner ?",
    formules: "Comment sont déduites cotisations sociales et CSG du brut ?",
    interpretation: "Que représente le net affiché avant prélèvement à la source ?",
    limitesCalcul: "Ce calcul brut vers net couvre-t-il tous les cas de paie ?",
    maillage: "Quels autres outils pour vérifier votre rémunération ?",
    exempleSection: "Exemple de conversion salaire brut vers net",
    exempleDonnees: "Quel salaire brut et taux de cotisations saisir ?",
    exempleCalcul: "Comment le simulateur déduit cotisations et CSG/CRDS ?",
    exempleResultat: "Quel salaire net pour un brut mensuel donné ?",
    exempleInterpretation: "Net avant impôt et net après PAS : que comparer ?",
    conseilsSection: "Conseils pour lire votre bulletin de paie",
    conseils: "Brut, net imposable et net à payer : que distinguer ?",
    limites: "Ce que ce simulateur ne remplace pas sur la paie",
  },
  "salaire-net-brut": {
    mainSection: "Comment retrouver le salaire brut à partir du net ?",
    definition: "Pourquoi reconstituer le brut à partir du net perçu ?",
    objectif: "Quand cette conversion net vers brut est-elle utile ?",
    variables: "Quel net cible, statut salarié et taux de cotisations ?",
    formules: "Comment le simulateur remonte du net au brut ?",
    interpretation: "Comment utiliser le brut calculé en négociation salariale ?",
    limitesCalcul: "Pourquoi le brut reconstitué peut différer de la paie réelle ?",
    maillage: "Quels simulateurs croiser pour une négociation salariale ?",
    exempleSection: "Exemple de conversion salaire net vers brut",
    exempleDonnees: "Quel salaire net cible et taux de cotisations ?",
    exempleCalcul: "Comment le simulateur reconstitue le brut mensuel ?",
    exempleResultat: "Quel brut demander pour obtenir un net donné ?",
    exempleInterpretation: "Net contractuel, primes et avantages : que retenir ?",
    conseilsSection: "Conseils pour négocier en salaire brut",
    conseils: "Net, brut et coût employeur : que mettre sur la table ?",
    limites: "Limites de cette conversion salaire net vers brut",
  },
  "cout-total-embauche-salarie": {
    mainSection: "Combien coûte réellement l'embauche d'un salarié ?",
    definition: "Qu'est-ce que le coût total pour l'employeur ?",
    objectif: "Pourquoi le super-brut dépasse le salaire versé au salarié ?",
    variables: "Quel salaire brut et taux de charges patronales renseigner ?",
    formules: "Comment sont calculées charges patronales et coût global ?",
    interpretation: "Que cache l'écart entre salaire brut et coût employeur ?",
    limitesCalcul: "Quels postes de coût ne sont pas toujours inclus ?",
    maillage: "Quels outils pour budgétiser une embauche ou une équipe ?",
    exempleSection: "Exemple de coût employeur pour un poste salarié",
    exempleDonnees: "Quel salaire brut et charges patronales saisir ?",
    exempleCalcul: "Comment le simulateur additionne salaire et charges ?",
    exempleResultat: "Quel budget annuel pour un poste à temps plein ?",
    exempleInterpretation: "Brut salarié, super-brut et masse salariale : que comparer ?",
    conseilsSection: "Conseils pour budgétiser une embauche",
    conseils: "CDI, CDD, alternance et primes : quels coûts intégrer ?",
    limites: "Ce que cette estimation ne couvre pas côté employeur",
  },
  "indemnites-licenciement": {
    mainSection: "Comment calculer ses indemnités de licenciement ?",
    definition: "Qu'est-ce que l'indemnité légale de licenciement ?",
    objectif: "Pourquoi estimer son indemnité avant l'entretien préalable ?",
    variables: "Quel salaire de référence, ancienneté et convention collective ?",
    formules: "Comment s'applique le barème légal de licenciement ?",
    interpretation: "Indemnité légale ou conventionnelle : laquelle s'applique ?",
    limitesCalcul: "Quels cas de licenciement échappent à ce barème ?",
    maillage: "Quels simulateurs utiles en cas de rupture de contrat ?",
    exempleSection: "Exemple de calcul d'indemnités de licenciement",
    exempleDonnees: "Quel salaire de référence et ancienneté saisir ?",
    exempleCalcul: "Comment le simulateur applique le barème légal ?",
    exempleResultat: "Quel montant d'indemnité selon votre ancienneté ?",
    exempleInterpretation: "Licenciement économique, faute ou inaptitude : que change-t-il ?",
    conseilsSection: "Conseils en cas de licenciement",
    conseils: "Préavis, CSP et rupture conventionnelle : quelles alternatives ?",
    limites: "Pourquoi faire valider le montant par un professionnel ?",
  },
  "conges-payes-acquis": {
    mainSection: "Combien de jours de congés payés ai-je acquis ?",
    definition: "Comment fonctionne l'acquisition des congés payés ?",
    objectif: "Pourquoi calculer ses droits sur la période de référence ?",
    variables: "Quelle période travaillée et calcul en jours ouvrables ou ouvrés ?",
    formules: "Comment est comptabilisé le nombre de jours de CP acquis ?",
    interpretation: "Congés ouvrables ou ouvrés : comment lire votre solde ?",
    limitesCalcul: "Quels absences ou contrats faussent le calcul ?",
    maillage: "Quels outils pour piloter son temps de travail ?",
    exempleSection: "Exemple d'acquisition de congés payés sur une période",
    exempleDonnees: "Quelle durée travaillée et mode de calcul saisir ?",
    exempleCalcul: "Comment le simulateur compte les jours acquis ?",
    exempleResultat: "Combien de jours de CP sur la période de référence ?",
    exempleInterpretation: "Congés pris, reportés et RTT : que vérifier ?",
    conseilsSection: "Conseils pour poser ses congés payés",
    conseils: "Fractionnement, report et convention collective : que retenir ?",
    limites: "Ce que ce calcul ne remplace pas auprès de l'employeur",
  },
  "ijss-arret-maladie": {
    mainSection: "Combien perçoit-on d'indemnités journalières en arrêt maladie ?",
    definition: "Que sont les indemnités journalières maladie (IJSS) ?",
    objectif: "Pourquoi anticiper ses IJSS avant un arrêt de travail ?",
    variables: "Quel salaire journalier de base et durée de l'arrêt ?",
    formules: "Comment la Sécurité sociale calcule-t-elle les IJSS ?",
    interpretation: "Que reste-t-il à percevoir après carence et plafonds ?",
    limitesCalcul: "Quand le maintien de salaire de l'employeur prime ?",
    maillage: "Quels simulateurs utiles pendant un arrêt de travail ?",
    exempleSection: "Exemple de calcul d'indemnités journalières maladie",
    exempleDonnees: "Quel salaire de référence et durée d'arrêt saisir ?",
    exempleCalcul: "Comment le simulateur applique carence et plafonds ?",
    exempleResultat: "Quel montant net d'IJSS par jour d'arrêt ?",
    exempleInterpretation: "Subrogation, complément employeur et CSG : que comparer ?",
    conseilsSection: "Conseils pendant un arrêt maladie",
    conseils: "Carence, déclaration et attestation : que faire rapidement ?",
    limites: "Pourquoi ce montant reste une estimation des IJSS",
  },
  "allocation-chomage-are": {
    mainSection: "Combien toucherait-on d'allocation chômage (ARE) ?",
    definition: "Qu'est-ce que l'allocation d'aide au retour à l'emploi ?",
    objectif: "Pourquoi estimer son ARE après une fin de contrat ?",
    variables: "Quel salaire de référence, ancienneté et droits ouverts ?",
    formules: "Comment Pôle emploi calcule-t-il le SJR et l'ARE ?",
    interpretation: "ARE pleine, dégressive ou minorée : que retenir ?",
    limitesCalcul: "Démission, CDD ou cumul emploi : quels effets sur l'ARE ?",
    maillage: "Quels outils pour préparer une période de chômage ?",
    exempleSection: "Exemple de calcul d'allocation chômage",
    exempleDonnees: "Quel salaire de référence et droits ouverts saisir ?",
    exempleCalcul: "Comment le simulateur calcule le SJR et l'ARE ?",
    exempleResultat: "Quel montant mensuel d'allocation chômage ?",
    exempleInterpretation: "Durée d'indemnisation et reprise d'activité : que prévoir ?",
    conseilsSection: "Conseils pour constituer son dossier France Travail",
    conseils: "Délai de carence, cumul et actualisation : que savoir ?",
    limites: "Ce que cette estimation ne remplace pas auprès de France Travail",
  },
  "heures-supplementaires": {
    mainSection: "Comment calculer la rémunération des heures supplémentaires ?",
    definition: "Qu'est-ce que la majoration des heures supplémentaires ?",
    objectif: "Pourquoi vérifier le supplément de salaire lié aux heures sup ?",
    variables: "Quel taux horaire, volume d'heures sup et majorations applicables ?",
    formules: "Comment sont payées les heures sup à 25 % et 50 % ?",
    interpretation: "Majoration légale ou conventionnelle : laquelle s'applique ?",
    limitesCalcul: "Contingent annuel et repos compensateur : que vérifier ?",
    maillage: "Quels simulateurs pour analyser sa rémunération globale ?",
    exempleSection: "Exemple de rémunération d'heures supplémentaires",
    exempleDonnees: "Quel taux horaire et volume d'heures sup saisir ?",
    exempleCalcul: "Comment le simulateur applique les majorations légales ?",
    exempleResultat: "Quel supplément de salaire pour vos heures sup ?",
    exempleInterpretation: "Heures sup, astreintes et repos : que distinguer ?",
    conseilsSection: "Conseils sur les heures supplémentaires",
    conseils: "Convention collective, repos et fiscalité : que contrôler ?",
    limites: "Pourquoi le bulletin de paie fait foi sur les heures sup",
  },
  "salaire-temps-partiel": {
    mainSection: "Comment calculer un salaire à temps partiel ?",
    definition: "Comment est proratisé le salaire en temps partiel ?",
    objectif: "Pourquoi estimer sa rémunération selon la quotité de travail ?",
    variables: "Quel salaire temps plein et pourcentage ou quotité partielle ?",
    formules: "Comment le simulateur proratise le salaire brut ou net ?",
    interpretation: "Mi-temps, quatre-cinquièmes : que change la quotité ?",
    limitesCalcul: "Heures complémentaires et minima légaux : que vérifier ?",
    maillage: "Quels outils pour comparer temps plein et temps partiel ?",
    exempleSection: "Exemple de salaire proratisé à temps partiel",
    exempleDonnees: "Quel salaire temps plein et quotité saisir ?",
    exempleCalcul: "Comment le simulateur proratise la rémunération ?",
    exempleResultat: "Quel salaire net pour une quotité réduite ?",
    exempleInterpretation: "Congés, retraite et droits sociaux en temps partiel ?",
    conseilsSection: "Conseils pour négocier un temps partiel",
    conseils: "Quotité, heures complémentaires et revenus du foyer : que peser ?",
    limites: "Ce que ce calcul ne remplace pas dans le contrat de travail",
  },
  "smic-net": {
    mainSection: "Quel est le SMIC net mensuel en 2026 ?",
    definition: "Quelle différence entre SMIC brut et SMIC net ?",
    objectif: "Pourquoi connaître le SMIC net avant prélèvement à la source ?",
    variables: "Quel SMIC horaire ou mensuel brut appliquer ?",
    formules: "Comment passe-t-on du SMIC brut au SMIC net ?",
    interpretation: "Votre salaire est-il au moins égal au SMIC net ?",
    limitesCalcul: "SMIC, minima conventionnels et primes : que comparer ?",
    maillage: "Quels simulateurs pour vérifier une rémunération au SMIC ?",
    exempleSection: "Exemple de calcul du SMIC net mensuel",
    exempleDonnees: "Quel SMIC brut horaire ou mensuel renseigner ?",
    exempleCalcul: "Comment le simulateur déduit cotisations du SMIC ?",
    exempleResultat: "Combien net avec le SMIC au taux en vigueur ?",
    exempleInterpretation: "Heures sup, primes et avantages au SMIC : que retenir ?",
    conseilsSection: "Conseils pour vérifier un salaire au SMIC",
    conseils: "Bulletin de paie, revalorisation et contestation : que faire ?",
    limites: "Pourquoi le SMIC net affiché peut varier légèrement",
  },
};
