import type { SimulatorHeadings } from "./types";

/** Titres H2/H3 rédigés individuellement — entreprise (10 simulateurs). */
export const entrepriseHeadings: Record<string, SimulatorHeadings> = {
  "calculateur-tjm-freelance": {
    mainSection: "Quel TJM facturer en freelance ?",
    definition: "Le taux journalier moyen, c'est quoi exactement ?",
    objectif: "Pourquoi partir de votre revenu net pour fixer un tarif ?",
    variables: "Revenu visé, jours facturés, charges pro : que renseigner ?",
    formules: "Du net au TJM : comment le simulateur remonte le tarif ?",
    interpretation: "Votre TJM minimum couvre-t-il vraiment vos charges ?",
    limitesCalcul: "Ce calcul de TJM ne tient pas compte de quoi ?",
    maillage: "TJM, coût horaire, CA objectif : quels outils croiser ?",
    exempleSection: "Exemple de calcul de TJM freelance",
    exempleDonnees: "Revenu net cible, charges et jours travaillés",
    exempleCalcul: "Étape par étape : du net au taux journalier",
    exempleResultat: "Le TJM à facturer pour tenir votre objectif",
    exempleInterpretation: "TJM théorique vs réel après congés et intercontrats",
    conseilsSection: "Bien fixer son tarif de consultant",
    conseils: "Intercontrat, TVA, retraite TNS : ce qu'il faut intégrer",
    limites: "Les approximations de ce simulateur de TJM",
  },
  "revenu-net-independant": {
    mainSection: "Combien reste-t-il net pour un indépendant ?",
    definition: "Revenu net d'un travailleur non salarié : de quoi parle-t-on ?",
    objectif: "Anticiper le net après cotisations URSSAF",
    variables: "Bénéfice, régime social, CSG : quels paramètres saisir ?",
    formules: "Comment le simulateur déduit charges et impôts du bénéfice ?",
    interpretation: "Que vous dit le net après cotisations sociales ?",
    limitesCalcul: "Pourquoi ce net TNS reste une estimation",
    maillage: "Revenu net, TJM, ACRE : simulateurs utiles pour un indépendant",
    exempleSection: "Exemple de revenu net pour un travailleur indépendant",
    exempleDonnees: "Bénéfice annuel et régime d'imposition choisi",
    exempleCalcul: "Du bénéfice au net : cotisations et CSG déduites",
    exempleResultat: "Le revenu net estimé après charges sociales",
    exempleInterpretation: "Micro, réel ou IS : pourquoi les résultats divergent",
    conseilsSection: "Optimiser son revenu d'indépendant",
    conseils: "Charges déductibles, PER, dividendes : les leviers à connaître",
    limites: "Ce que ce simulateur ne peut pas prévoir",
  },
  "sasu-remuneration-dividendes": {
    mainSection: "Salaire ou dividendes en SASU : que choisir ?",
    definition: "Rémunération et dividendes en SASU : quelle différence ?",
    objectif: "Comparer le net après impôt et charges sociales",
    variables: "PFU ou barème : quelle fiscalité pour les dividendes ?",
    formules: "Comment le simulateur met salaire et dividendes en parallèle ?",
    interpretation: "Quel est le meilleur choix entre salaire et dividendes ?",
    limitesCalcul: "Pourquoi cette comparaison SASU reste indicative",
    maillage: "Quels autres simulateurs pour un dirigeant de SASU ?",
    exempleSection: "Exemple de calcul salaire vs dividendes en SASU",
    exempleDonnees: "Montant distribuable, part salaire et part dividendes",
    exempleCalcul: "Charges sociales, impôt sur le revenu et net final",
    exempleResultat: "Quelle option laisse le plus de net en poche ?",
    exempleInterpretation: "Assurance maladie et retraite : l'autre face de l'arbitrage",
    conseilsSection: "Arbitrer entre salaire et dividendes en SASU",
    conseils: "Plafonds sécurité sociale, holding et trésorerie : points de vigilance",
    limites: "Les limites d'une comparaison rémunération / dividendes",
  },
  "portage-salarial-vs-freelance": {
    mainSection: "Portage salarial ou freelance : lequel paie le mieux ?",
    definition: "Portage salarial et auto-entrepreneur : deux statuts, deux logiques",
    objectif: "Comparer le net perçu selon votre mode d'exercice",
    variables: "CA, frais de gestion, charges : que renseigner pour chaque statut ?",
    formules: "Sur quels postes le simulateur compare portage et freelance ?",
    interpretation: "L'écart de revenu net, est-il vraiment décisif ?",
    limitesCalcul: "Ce que cette comparaison ne couvre pas",
    maillage: "Statut, TJM, revenu net : quels simulateurs enchaîner ?",
    exempleSection: "Exemple comparatif portage salarial vs freelance",
    exempleDonnees: "Chiffre d'affaires et frais de gestion du portage",
    exempleCalcul: "Net après charges pour chaque statut, côte à côte",
    exempleResultat: "Quel statut maximise le net sur votre CA ?",
    exempleInterpretation: "Protection sociale, simplicité admin : au-delà du net",
    conseilsSection: "Choisir entre portage et freelance",
    conseils: "Chômage, retraite, TVA : les critères qui ne figurent pas sur la fiche de paie",
    limites: "Pourquoi ce comparatif reste une photographie à un instant T",
  },
  "seuil-franchise-tva": {
    mainSection: "Franchise en base de TVA : suis-je encore en dessous du seuil ?",
    definition: "La franchise en base de TVA, en bref",
    objectif: "Savoir si vous devez commencer à facturer la TVA",
    variables: "CA, activité BIC ou BNC, prestations de services : que saisir ?",
    formules: "Comment le simulateur vérifie le dépassement des plafonds ?",
    interpretation: "Franchise, seuil dépassé ou zone de tolérance : où en êtes-vous ?",
    limitesCalcul: "Ce contrôle de seuils TVA ne remplace pas un expert-comptable",
    maillage: "TVA, micro-entreprise, facturation : simulateurs à croiser",
    exempleSection: "Exemple de contrôle de franchise TVA pour un prestataire",
    exempleDonnees: "CA annuel et type d'activité exercée",
    exempleCalcul: "Comparaison de votre CA aux plafonds en vigueur",
    exempleResultat: "Devez-vous facturer la TVA à vos clients ?",
    exempleInterpretation: "Seuils majorés et dépassement ponctuel : ce qu'il faut savoir",
    conseilsSection: "Gérer la TVA en micro-entreprise",
    conseils: "Option pour la TVA, régularisation et dépassement : comment réagir",
    limites: "Les cas où cette vérification de franchise ne suffit pas",
  },
  "break-even-entreprise": {
    mainSection: "À partir de quel CA mon activité devient rentable ?",
    definition: "Le point mort (break-even), c'est quoi ?",
    objectif: "Connaître le chiffre d'affaires minimum pour couvrir vos charges",
    variables: "Coûts fixes, marge unitaire, charges variables : les entrées clés",
    formules: "Comment est calculé le seuil de rentabilité ?",
    interpretation: "Votre CA actuel est-il au-dessus ou en dessous du point mort ?",
    limitesCalcul: "Pourquoi le break-even calculé peut diverger de la réalité",
    maillage: "Rentabilité, marge commerciale, CA objectif : outils complémentaires",
    exempleSection: "Exemple de seuil de rentabilité pour une activité de services",
    exempleDonnees: "Coûts fixes mensuels et marge sur chaque vente",
    exempleCalcul: "Du coût fixe au CA break-even en quelques étapes",
    exempleResultat: "Le chiffre d'affaires minimum pour être à l'équilibre",
    exempleInterpretation: "Marge de sécurité et levier opérationnel : lire les résultats",
    conseilsSection: "Atteindre plus vite le seuil de rentabilité",
    conseils: "Baisser les coûts fixes ou augmenter la marge : par où commencer",
    limites: "Les hypothèses simplificatrices de ce calcul de point mort",
  },
  "marge-commerciale-taux": {
    mainSection: "Quelle marge commerciale sur vos produits ?",
    definition: "Marge commerciale : montant et taux, quelle différence ?",
    objectif: "Mesurer l'écart entre prix de vente et coût d'achat",
    variables: "Prix de vente HT et coût d'achat HT à renseigner",
    formules: "Comment sont calculés la marge en euros et le taux en % ?",
    interpretation: "Votre taux de marge est-il suffisant pour couvrir vos charges ?",
    limitesCalcul: "Ce calcul de marge ne prend pas tout en compte",
    maillage: "Marge, break-even, CA objectif : simulateurs pour piloter son commerce",
    exempleSection: "Exemple de calcul de marge commerciale sur un produit",
    exempleDonnees: "Prix de vente HT et coût d'achat HT du produit",
    exempleCalcul: "Marge en euros puis conversion en taux de marge",
    exempleResultat: "Le taux de marge commerciale obtenu",
    exempleInterpretation: "Marge commerciale et taux de marque : ne pas confondre",
    conseilsSection: "Améliorer sa marge commerciale",
    conseils: "Remises clients, logistique et TVA : ce qui grignote la marge",
    limites: "Les limites d'un calcul de marge sur un seul produit",
  },
  "cout-horaire-charge-tns": {
    mainSection: "Quel tarif horaire facturer en indépendant ?",
    definition: "Coût horaire chargé pour un TNS : de quoi s'agit-il ?",
    objectif: "Intégrer cotisations sociales et charges fixes dans votre tarif",
    variables: "Revenu net visé, heures travaillées, taux de cotisations",
    formules: "Comment le simulateur reconstitue le coût horaire chargé ?",
    interpretation: "Votre tarif horaire couvre-t-il charges et temps non facturé ?",
    limitesCalcul: "Pourquoi ce taux horaire reste une base de travail",
    maillage: "Coût horaire, TJM, facturation : les simulateurs à enchaîner",
    exempleSection: "Exemple de calcul du coût horaire chargé TNS",
    exempleDonnees: "Revenu net mensuel visé et heures facturables",
    exempleCalcul: "Du net au taux horaire en intégrant les cotisations",
    exempleResultat: "Le tarif horaire minimum à facturer",
    exempleInterpretation: "Heures admin, prospection et congés : l'angle mort du calcul",
    conseilsSection: "Fixer un tarif horaire cohérent",
    conseils: "TJM, forfait projet et négociation client : trois approches",
    limites: "Ce que ce simulateur de coût horaire ne modélise pas",
  },
  "exoneration-acre": {
    mainSection: "Combien l'ACRE vous fait-il économiser de charges ?",
    definition: "L'ACRE : l'exonération de cotisations au lancement",
    objectif: "Estimer l'économie de charges la première année d'activité",
    variables: "CA prévisionnel, type d'activité, durée de l'exonération",
    formules: "Comment le simulateur calcule le montant exonéré ?",
    interpretation: "Quel impact réel de l'ACRE sur vos cotisations ?",
    limitesCalcul: "Les conditions d'éligibilité que le simulateur ne vérifie pas toutes",
    maillage: "ACRE, charges micro, revenu net : simulateurs pour bien démarrer",
    exempleSection: "Exemple d'exonération ACRE en micro-entreprise",
    exempleDonnees: "CA annuel et activité exercée (BIC ou BNC)",
    exempleCalcul: "Application du taux d'exonération sur les cotisations dues",
    exempleResultat: "L'économie de charges estimée avec l'ACRE",
    exempleInterpretation: "Création d'entreprise, cumuls et fin d'exonération : le calendrier",
    conseilsSection: "Tirer parti de l'ACRE au lancement",
    conseils: "Cumul avec d'autres aides, plafonds et passage au taux plein : à anticiper",
    limites: "Pourquoi cette estimation ACRE ne vaut pas confirmation URSSAF",
  },
  "facturation-objectif-revenu-net": {
    mainSection: "Quel CA viser pour toucher le net que vous voulez ?",
    definition: "Le lien entre chiffre d'affaires et revenu net d'indépendant",
    objectif: "Dimensionner sa facturation selon un objectif de revenu net",
    variables: "Revenu net cible, structure de charges, taux de cotisations",
    formules: "Comment le simulateur remonte du net au CA nécessaire ?",
    interpretation: "Votre CA actuel suffit-il pour atteindre votre objectif net ?",
    limitesCalcul: "Les imprévus que cette projection ne couvre pas",
    maillage: "CA objectif, TJM, revenu net : piloter sa facturation au quotidien",
    exempleSection: "Exemple de CA à facturer pour un revenu net cible",
    exempleDonnees: "Revenu net mensuel visé et charges professionnelles",
    exempleCalcul: "Du net souhaité au CA brut à facturer",
    exempleResultat: "Le chiffre d'affaires annuel à atteindre",
    exempleInterpretation: "CA brut, TVA et trésorerie : trois notions à ne pas mélanger",
    conseilsSection: "Piloter son chiffre d'affaires au fil de l'année",
    conseils: "Saisonnalité, impayés et provisions : garder une marge de manœuvre",
    limites: "Les limites d'une projection de CA à partir d'un net cible",
  },
};
