import type { SimulatorHeadings } from "./types";

/** Titres H2/H3 rédigés individuellement — finance (10 simulateurs). */
export const financeHeadings: Record<string, SimulatorHeadings> = {
  "mensualite-credit-consommation": {
    mainSection: "Comment calculer la mensualité d'un crédit consommation ?",
    definition: "Qu'est-ce que la mensualité d'un prêt à la consommation ?",
    objectif: "Pourquoi estimer la mensualité avant de souscrire un crédit ?",
    variables: "Quel montant emprunté, taux d'intérêt et durée renseigner ?",
    formules: "Comment est calculée une mensualité de crédit constante ?",
    interpretation: "Que représente la mensualité par rapport au coût total ?",
    limitesCalcul: "Assurance emprunteur et frais de dossier : inclus ou non ?",
    maillage: "Quels outils pour comparer plusieurs crédits conso ?",
    exempleSection: "Exemple de mensualité pour un crédit consommation",
    exempleDonnees: "Quel capital, taux et durée saisir ?",
    exempleCalcul: "Comment le simulateur calcule la mensualité constante ?",
    exempleResultat: "Quelle mensualité pour un emprunt conso donné ?",
    exempleInterpretation: "TAEG, durée et assurance : que comparer entre offres ?",
    conseilsSection: "Conseils avant un crédit à la consommation",
    conseils: "Taux d'usure, durée et surendettement : que vérifier ?",
    limites: "Ce que cette simulation ne remplace pas chez le prêteur",
  },
  "interets-composes": {
    mainSection: "Comment calculer les intérêts composés sur un placement ?",
    definition: "Qu'est-ce que la capitalisation composée des intérêts ?",
    objectif: "Pourquoi projeter la croissance d'un capital investi dans le temps ?",
    variables: "Quel capital initial, versements, taux et durée de placement ?",
    formules: "Comment les intérêts composés s'accumulent-ils chaque période ?",
    interpretation: "Que montre la courbe de capitalisation sur le long terme ?",
    limitesCalcul: "Rendement fixe et inflation : quelles hypothèses simplifiées ?",
    maillage: "Quels simulateurs pour comparer vos placements ?",
    exempleSection: "Exemple de capitalisation avec intérêts composés",
    exempleDonnees: "Quel capital, taux annuel et durée saisir ?",
    exempleCalcul: "Comment le simulateur capitalise les intérêts chaque année ?",
    exempleResultat: "Quel capital final après plusieurs années de placement ?",
    exempleInterpretation: "Effet du temps et des versements réguliers : que retenir ?",
    conseilsSection: "Conseils pour profiter des intérêts composés",
    conseils: "Fréquence de capitalisation, frais et inflation : que intégrer ?",
    limites: "Pourquoi les performances passées ne garantissent rien",
  },
  "simulateur-inflation": {
    mainSection: "Quel est l'impact de l'inflation sur mon pouvoir d'achat ?",
    definition: "Comment l'inflation érode-t-elle le pouvoir d'achat ?",
    objectif: "Pourquoi estimer la valeur réelle d'une somme dans le futur ?",
    variables: "Quel montant initial, taux d'inflation et horizon de temps ?",
    formules: "Comment est mesurée la perte de pouvoir d'achat ?",
    interpretation: "Que vaut votre argent en prix constants dans dix ans ?",
    limitesCalcul: "Inflation moyenne ou personnalisée : quelle limite ?",
    maillage: "Quels outils pour protéger son épargne de l'inflation ?",
    exempleSection: "Exemple d'érosion du pouvoir d'achat par l'inflation",
    exempleDonnees: "Quel montant, taux d'inflation et durée saisir ?",
    exempleCalcul: "Comment le simulateur actualise le pouvoir d'achat ?",
    exempleResultat: "Quelle valeur réelle de votre épargne dans le futur ?",
    exempleInterpretation: "Inflation, épargne liquide et salaires : comment réagir ?",
    conseilsSection: "Conseils pour préserver son pouvoir d'achat",
    conseils: "Indexation, placements réels et diversification : que retenir ?",
    limites: "Pourquoi l'inflation future reste incertaine",
  },
  "budget-reste-a-vivre": {
    mainSection: "Combien me reste-t-il à vivre après mes charges ?",
    definition: "Qu'est-ce que le reste à vivre mensuel ?",
    objectif: "Pourquoi calculer le reste à vivre avant un projet de crédit ?",
    variables: "Quels revenus nets et charges fixes mensuelles renseigner ?",
    formules: "Comment est calculé le reste à vivre du foyer ?",
    interpretation: "Votre reste à vivre est-il confortable pour emprunter ?",
    limitesCalcul: "Charges variables et imprévus : que ne compte pas le calcul ?",
    maillage: "Quels simulateurs pour préparer un dossier bancaire ?",
    exempleSection: "Exemple de calcul du reste à vivre d'un foyer",
    exempleDonnees: "Quels revenus et charges mensuelles renseigner ?",
    exempleCalcul: "Comment le simulateur soustrait charges et crédits ?",
    exempleResultat: "Quel budget disponible après toutes les charges ?",
    exempleInterpretation: "Reste à vivre bancaire : quel seuil viser ?",
    conseilsSection: "Conseils pour améliorer son reste à vivre",
    conseils: "Charges fixes, crédits et épargne de précaution : que optimiser ?",
    limites: "Ce que les banques regardent au-delà du reste à vivre",
  },
  "simulateur-retraite": {
    mainSection: "Combien vais-je toucher à la retraite ?",
    definition: "Comment est estimée la pension de retraite ?",
    objectif: "Pourquoi projeter ses revenus à la retraite dès maintenant ?",
    variables: "Quel salaire, trimestres validés et âge de départ ?",
    formules: "Comment le simulateur estime-t-il pension base et complémentaire ?",
    interpretation: "Votre pension projetée suffit-elle à maintenir votre niveau de vie ?",
    limitesCalcul: "Réformes, carrière atypique et trimestres manquants : quels biais ?",
    maillage: "Quels outils pour compléter votre préparation retraite ?",
    exempleSection: "Exemple de projection de pension de retraite",
    exempleDonnees: "Quel salaire et parcours professionnel renseigner ?",
    exempleCalcul: "Comment le simulateur estime base et complémentaire ?",
    exempleResultat: "Quel revenu mensuel estimé au départ à la retraite ?",
    exempleInterpretation: "Retraite de base, complémentaire et épargne : que combiner ?",
    conseilsSection: "Conseils pour préparer sa retraite",
    conseils: "Trimestres, rachat et PER : quels leviers activer ?",
    limites: "Pourquoi utiliser aussi le simulateur officiel M@rel",
  },
  "rendement-livret-a": {
    mainSection: "Quel rendement obtenir sur un Livret A ?",
    definition: "Comment fonctionne le rendement du Livret A réglementé ?",
    objectif: "Pourquoi estimer les intérêts annuels sur son livret ?",
    variables: "Quel solde, taux Livret A et durée de placement ?",
    formules: "Comment sont calculés les intérêts du Livret A ?",
    interpretation: "Le Livret A compense-t-il l'inflation sur votre épargne ?",
    limitesCalcul: "Plafond, double détente et fiscalité : que ne modélise pas le calcul ?",
    maillage: "Quels placements comparer au Livret A ?",
    exempleSection: "Exemple de rendement sur un Livret A",
    exempleDonnees: "Quel capital et taux Livret A saisir ?",
    exempleCalcul: "Comment le simulateur calcule les intérêts annuels ?",
    exempleResultat: "Combien d'intérêts nets sur votre Livret A ?",
    exempleInterpretation: "Livret A, LDDS et assurance-vie : que choisir pour l'épargne de précaution ?",
    conseilsSection: "Conseils pour optimiser son Livret A",
    conseils: "Plafond, versements réguliers et double détente : que savoir ?",
    limites: "Ce que ce calcul ne remplace pas sur votre relevé bancaire",
  },
  "rendement-pea": {
    mainSection: "Quel rendement espérer sur un PEA ?",
    definition: "Qu'est-ce que le Plan d'Épargne en Actions (PEA) ?",
    objectif: "Pourquoi projeter la performance d'un PEA sur plusieurs années ?",
    variables: "Quel capital initial, versements, rendement et durée ?",
    formules: "Comment est projetée la valorisation d'un PEA ?",
    interpretation: "Que change la fiscalité après cinq ans de détention ?",
    limitesCalcul: "Rendement hypothétique et volatilité : quels risques ?",
    maillage: "Quels outils pour comparer PEA et compte-titres ?",
    exempleSection: "Exemple de projection de rendement sur un PEA",
    exempleDonnees: "Quel capital initial, versements et rendement ?",
    exempleCalcul: "Comment le simulateur capitalise les gains du PEA ?",
    exempleResultat: "Quelle valorisation PEA après plusieurs années ?",
    exempleInterpretation: "PEA, assurance-vie et CTO : quels avantages fiscaux ?",
    conseilsSection: "Conseils pour investir via un PEA",
    conseils: "Durée, diversification et retrait : que retenir ?",
    limites: "Pourquoi les marchés actions ne suivent pas une courbe lisse",
  },
  "cout-total-credit-consommation": {
    mainSection: "Quel est le coût total d'un crédit à la consommation ?",
    definition: "Qu'appelle-t-on le coût total d'un crédit conso ?",
    objectif: "Pourquoi regarder au-delà de la mensualité affichée ?",
    variables: "Quel capital emprunté, taux et durée du crédit ?",
    formules: "Comment sont calculés intérêts et montant total remboursé ?",
    interpretation: "Le surcoût du crédit est-il acceptable pour votre budget ?",
    limitesCalcul: "Assurance, frais et pénalités : toujours inclus ?",
    maillage: "Quels simulateurs pour négocier ou comparer un crédit conso ?",
    exempleSection: "Exemple de coût total d'un crédit consommation",
    exempleDonnees: "Quel montant, taux et durée saisir ?",
    exempleCalcul: "Comment le simulateur additionne capital et intérêts ?",
    exempleResultat: "Combien coûte réellement ce crédit sur toute sa durée ?",
    exempleInterpretation: "TAEG, durée courte ou longue : que privilégier ?",
    conseilsSection: "Conseils pour limiter le coût d'un crédit conso",
    conseils: "Renégociation, remboursement anticipé et rachat : quelles options ?",
    limites: "Ce que le contrat de prêt peut ajouter au coût affiché",
  },
  "loa-vs-credit-auto": {
    mainSection: "LOA ou crédit auto : comment comparer les coûts ?",
    definition: "Quelle différence entre LOA et crédit automobile ?",
    objectif: "Pourquoi comparer le coût global de chaque mode de financement ?",
    variables: "Quel prix du véhicule, apport, durée et taux pour chaque option ?",
    formules: "Quels coûts comparer entre LOA et crédit classique ?",
    interpretation: "Quelle option coûte le moins cher selon votre usage ?",
    limitesCalcul: "Kilométrage, entretien et valeur de revente : inclus ?",
    maillage: "Quels outils pour budgétiser l'achat d'un véhicule ?",
    exempleSection: "Exemple comparatif LOA et crédit auto",
    exempleDonnees: "Quel prix, apport et conditions LOA / crédit ?",
    exempleCalcul: "Comment le simulateur compare les deux scénarios ?",
    exempleResultat: "LOA ou crédit : quelle option la moins chère au total ?",
    exempleInterpretation: "Rachat final LOA ou propriété directe : que choisir ?",
    conseilsSection: "Conseils pour choisir entre LOA et crédit auto",
    conseils: "Kilométrage, entretien et revente : que intégrer au choix ?",
    limites: "Pourquoi lire aussi les conditions générales du contrat",
  },
  "frais-kilometriques": {
    mainSection: "Combien puis-je déduire avec les frais kilométriques ?",
    definition: "Qu'est-ce que l'indemnité kilométrique déductible ?",
    objectif: "Pourquoi estimer l'abattement fiscal lié à vos trajets professionnels ?",
    variables: "Quelle distance annuelle, puissance fiscale et barème applicable ?",
    formules: "Comment le barème fiscal calcule-t-il les frais kilométriques ?",
    interpretation: "Barème kilométrique ou frais réels : lequel est plus avantageux ?",
    limitesCalcul: "Justificatifs, véhicule de fonction et changement de barème : quoi ?",
    maillage: "Quels simulateurs pour préparer sa déclaration de revenus ?",
    exempleSection: "Exemple de déduction au barème kilométrique",
    exempleDonnees: "Quelle distance parcourue et puissance fiscale saisir ?",
    exempleCalcul: "Comment le simulateur applique le barème fiscal ?",
    exempleResultat: "Quel montant de frais kilométriques déductibles ?",
    exempleInterpretation: "Auto-entrepreneur, salarié et BNC : mêmes règles ?",
    conseilsSection: "Conseils pour optimiser les frais kilométriques",
    conseils: "Carnet de bord, changement de véhicule et option réelle : que retenir ?",
    limites: "Pourquoi conserver vos justificatifs en cas de contrôle",
  },
};
