import type { SimulatorHeadings } from "./types";

/** Titres H2/H3 rédigés individuellement — fiscalité (10 simulateurs). */
export const fiscaliteHeadings: Record<string, SimulatorHeadings> = {
  "impot-sur-le-revenu": {
    mainSection: "Comment estimer son impôt sur le revenu ?",
    definition: "Comment fonctionne l'impôt sur le revenu en France ?",
    objectif: "Pourquoi anticiper l'impôt avant la déclaration annuelle ?",
    variables: "Quels revenus, parts fiscales et déductions renseigner ?",
    formules: "Comment s'applique le barème progressif de l'impôt ?",
    interpretation: "Impôt brut, décote et crédits : que retenir du résultat ?",
    limitesCalcul: "Réductions, crédits d'impôt et cas particuliers : tous inclus ?",
    maillage: "Quels outils pour affiner sa déclaration de revenus ?",
    exempleSection: "Exemple d'estimation de l'impôt sur le revenu",
    exempleDonnees: "Quels revenus et quotient familial saisir ?",
    exempleCalcul: "Comment le simulateur applique tranches et décote ?",
    exempleResultat: "Quel impôt sur le revenu pour votre foyer ?",
    exempleInterpretation: "Crédits d'impôt et réductions : que intégrer ensuite ?",
    conseilsSection: "Conseils pour optimiser son impôt sur le revenu",
    conseils: "Déductions, PER et niches fiscales : quels leviers légaux ?",
    limites: "Pourquoi cette estimation ne remplace pas impots.gouv.fr",
  },
  "quotient-familial": {
    mainSection: "Comment calculer son quotient familial ?",
    definition: "Qu'est-ce que le quotient familial fiscal ?",
    objectif: "Pourquoi connaître son nombre de parts avant l'impôt ?",
    variables: "Quelle situation familiale et personnes à charge renseigner ?",
    formules: "Comment est calculé le nombre de parts fiscales ?",
    interpretation: "Combien de parts pour votre foyer et quel effet sur l'impôt ?",
    limitesCalcul: "Plafonnement du quotient : quand l'avantage diminue ?",
    maillage: "Quels simulateurs utiles avec le quotient familial ?",
    exempleSection: "Exemple de calcul du quotient familial",
    exempleDonnees: "Quelle composition du foyer renseigner ?",
    exempleCalcul: "Comment le simulateur attribue les parts fiscales ?",
    exempleResultat: "Combien de parts fiscales pour votre situation ?",
    exempleInterpretation: "Enfants, garde alternée et invalidité : que change-t-il ?",
    conseilsSection: "Conseils sur le quotient familial",
    conseils: "Naissance, mariage et changement de situation : que déclarer ?",
    limites: "Ce que ce calcul ne remplace pas sur votre avis d'impôt",
  },
  "prelevement-a-la-source": {
    mainSection: "Comment est calculé le prélèvement à la source ?",
    definition: "Qu'est-ce que le prélèvement à la source de l'impôt ?",
    objectif: "Pourquoi estimer le montant prélevé sur votre salaire ?",
    variables: "Quel revenu net imposable et taux de PAS appliqué ?",
    formules: "Comment est calculé le prélèvement à la source mensuel ?",
    interpretation: "Taux neutre, individualisé ou personnalisé : lequel choisir ?",
    limitesCalcul: "Revenus variables et plusieurs employeurs : quels écarts ?",
    maillage: "Quels outils pour ajuster son impôt sur l'année ?",
    exempleSection: "Exemple de calcul du prélèvement à la source",
    exempleDonnees: "Quel revenu et taux de PAS saisir ?",
    exempleCalcul: "Comment le simulateur applique le taux retenu ?",
    exempleResultat: "Quel montant de PAS prélevé chaque mois ?",
    exempleInterpretation: "Régularisation en avril : trop-perçu ou reste à payer ?",
    conseilsSection: "Conseils pour ajuster son taux de PAS",
    conseils: "Modifier le taux sur impots.gouv.fr : quand le faire ?",
    limites: "Pourquoi le taux affiché peut évoluer en cours d'année",
  },
  "flat-tax-30-pourcent": {
    mainSection: "Flat tax 30 % : combien d'impôt sur vos placements ?",
    definition: "Qu'est-ce que la flat tax (PFU) à 30 % ?",
    objectif: "Pourquoi comparer PFU et barème sur vos revenus du capital ?",
    variables: "Quels dividendes, intérets ou plus-values mobilières ?",
    formules: "Comment se décompose la flat tax à 30 % ?",
    interpretation: "PFU ou option au barème : quelle option paie moins ?",
    limitesCalcul: "Plus-values, assurance-vie et PEA : mêmes règles ?",
    maillage: "Quels simulateurs pour la fiscalité de vos placements ?",
    exempleSection: "Exemple de calcul de la flat tax sur des revenus financiers",
    exempleDonnees: "Quel montant de revenus financiers saisir ?",
    exempleCalcul: "Comment le simulateur applique prélèvement et prélèvements sociaux ?",
    exempleResultat: "Quel impôt avec le PFU sur vos placements ?",
    exempleInterpretation: "Option barème : dans quels cas devient-elle intéressante ?",
    conseilsSection: "Conseils sur la fiscalité des revenus du capital",
    conseils: "PEA, assurance-vie et dividendes : que comparer ?",
    limites: "Ce que ce calcul ne remplace pas sur votre IFU",
  },
  "micro-entrepreneur-charges": {
    mainSection: "Quelles charges sociales en micro-entreprise ?",
    definition: "Comment sont calculées les cotisations du micro-entrepreneur ?",
    objectif: "Pourquoi estimer les charges URSSAF sur votre chiffre d'affaires ?",
    variables: "Quel chiffre d'affaires, activité et taux de cotisations ?",
    formules: "Comment l'URSSAF calcule-t-elle les cotisations micro ?",
    interpretation: "Que couvrent concrètement vos cotisations micro-entreprise ?",
    limitesCalcul: "Plafonds, ACRE et versement libératoire : pris en compte ?",
    maillage: "Quels outils pour piloter une micro-entreprise ?",
    exempleSection: "Exemple de calcul des charges micro-entrepreneur",
    exempleDonnees: "Quel CA et type d'activité renseigner ?",
    exempleCalcul: "Comment le simulateur applique le taux URSSAF ?",
    exempleResultat: "Quel montant de cotisations sur votre CA ?",
    exempleInterpretation: "CAF, retraite et CFP : que financent vos cotisations ?",
    conseilsSection: "Conseils pour gérer ses charges micro-entreprise",
    conseils: "Plafonds, ACRE et versement libératoire : que retenir ?",
    limites: "Pourquoi vérifier aussi sur autoentrepreneur.urssaf.fr",
  },
  "credit-impot-emploi-domicile": {
    mainSection: "Quel crédit d'impôt pour l'emploi d'un salarié à domicile ?",
    definition: "Qu'est-ce que le crédit d'impôt emploi à domicile ?",
    objectif: "Pourquoi estimer l'avantage fiscal d'une aide à domicile ?",
    variables: "Quelles dépenses éligibles et plafond applicable ?",
    formules: "Comment est calculé le crédit d'impôt à 50 % ?",
    interpretation: "Quelle économie d'impôt pour vos dépenses à domicile ?",
    limitesCalcul: "Plafonds, CESU et services éligibles : tous couverts ?",
    maillage: "Quels simulateurs utiles pour l'emploi à domicile ?",
    exempleSection: "Exemple de crédit d'impôt pour emploi à domicile",
    exempleDonnees: "Quel montant de dépenses éligibles saisir ?",
    exempleCalcul: "Comment le simulateur calcule 50 % de crédit ?",
    exempleResultat: "Quel crédit d'impôt pour vos dépenses à domicile ?",
    exempleInterpretation: "CESU, garde d'enfants et ménage : que couvre le crédit ?",
    conseilsSection: "Conseils pour bénéficier du crédit d'impôt",
    conseils: "Attestation fiscale, plafonds et CESU : que vérifier ?",
    limites: "Ce que l'administration peut contrôler sur vos justificatifs",
  },
  "impot-dividendes": {
    mainSection: "Quel impôt payer sur des dividendes perçus ?",
    definition: "Comment sont fiscalisés les dividendes en France ?",
    objectif: "Pourquoi comparer PFU et barème sur vos dividendes ?",
    variables: "Quel montant de dividendes bruts et option fiscale choisie ?",
    formules: "Comment est calculé l'impôt sur les dividendes ?",
    interpretation: "PFU ou barème avec abattement : quelle option retenir ?",
    limitesCalcul: "PEA, holding et dividendes étrangers : mêmes règles ?",
    maillage: "Quels outils pour optimiser la fiscalité de vos dividendes ?",
    exempleSection: "Exemple de calcul de l'impôt sur les dividendes",
    exempleDonnees: "Quel montant de dividendes et option saisir ?",
    exempleCalcul: "Comment le simulateur compare PFU et barème ?",
    exempleResultat: "Quel impôt net sur vos dividendes ?",
    exempleInterpretation: "Abattement de 40 % et CSG déductible : que retenir ?",
    conseilsSection: "Conseils pour optimiser la fiscalité des dividendes",
    conseils: "SASU, holding et PEA : quelles stratégies envisager ?",
    limites: "Pourquoi valider le choix fiscal avec un expert-comptable",
  },
  "taux-marginal-imposition": {
    mainSection: "Quel est mon taux marginal d'imposition (TMI) ?",
    definition: "Qu'est-ce que le taux marginal d'imposition ?",
    objectif: "Pourquoi connaître sa tranche la plus élevée d'impôt ?",
    variables: "Quel revenu imposable par part fiscale renseigner ?",
    formules: "Comment est déterminée la tranche marginale d'imposition ?",
    interpretation: "TMI et taux moyen : quelle différence pour vos arbitrages ?",
    limitesCalcul: "Plafonnement du quotient et revenus exceptionnels : quels effets ?",
    maillage: "Quels simulateurs pour optimiser selon votre TMI ?",
    exempleSection: "Exemple de calcul du taux marginal d'imposition",
    exempleDonnees: "Quel revenu net imposable par part saisir ?",
    exempleCalcul: "Comment le simulateur identifie la tranche marginale ?",
    exempleResultat: "Quel TMI pour votre niveau de revenu ?",
    exempleInterpretation: "PER, déficit foncier et donations : quels arbitrages selon le TMI ?",
    conseilsSection: "Conseils pour utiliser son TMI",
    conseils: "Quand le TMI guide-t-il vos choix de défiscalisation ?",
    limites: "Pourquoi le TMI seul ne suffit pas à décider",
  },
  "donation-numeraire": {
    mainSection: "Quels droits de donation pour un don en numéraire ?",
    definition: "Comment sont taxés les dons en numéraire entre proches ?",
    objectif: "Pourquoi estimer la fiscalité avant un don d'argent ?",
    variables: "Quel montant du don, lien de parenté et abattements disponibles ?",
    formules: "Comment sont calculés les droits de donation ?",
    interpretation: "Quel coût fiscal pour transmettre de l'argent à un proche ?",
    limitesCalcul: "Abattements renouvelables et donations antérieures : pris en compte ?",
    maillage: "Quels outils pour préparer une transmission patrimoniale ?",
    exempleSection: "Exemple de calcul des droits sur une donation en numéraire",
    exempleDonnees: "Quel montant, bénéficiaire et abattements saisir ?",
    exempleCalcul: "Comment le simulateur applique barème et abattements ?",
    exempleResultat: "Quel montant de droits pour ce don en numéraire ?",
    exempleInterpretation: "Don familial, pacte Dutreil et démembrement : quelles pistes ?",
    conseilsSection: "Conseils pour transmettre par donation",
    conseils: "Abattements renouvelables tous les 15 ans : que retenir ?",
    limites: "Pourquoi faire valider une donation par un notaire",
  },
  "cesu-credit-impot": {
    mainSection: "Quel crédit d'impôt avec le CESU préfinancé ?",
    definition: "Qu'est-ce que le CESU et le crédit d'impôt associé ?",
    objectif: "Pourquoi estimer l'avantage fiscal du CESU employeur ?",
    variables: "Quel montant de CESU reçu et dépenses éligibles ?",
    formules: "Comment est calculé le crédit d'impôt lié au CESU ?",
    interpretation: "Quelle économie d'impôt avec le CESU préfinancé ?",
    limitesCalcul: "Plafonds employeur et services éligibles : tous couverts ?",
    maillage: "Quels simulateurs croiser avec le CESU et l'emploi à domicile ?",
    exempleSection: "Exemple de crédit d'impôt avec le CESU préfinancé",
    exempleDonnees: "Quel montant CESU et dépenses saisir ?",
    exempleCalcul: "Comment le simulateur calcule le crédit d'impôt ?",
    exempleResultat: "Quelle économie d'impôt avec le CESU ?",
    exempleInterpretation: "CESU et crédit emploi à domicile : comment cumuler ?",
    conseilsSection: "Conseils pour utiliser le CESU",
    conseils: "Plafonds employeur, services éligibles et attestation : que vérifier ?",
    limites: "Ce que ce calcul ne remplace pas sur votre déclaration",
  },
};
