import type { SimulatorHeadings } from "./types";

/** Titres H2/H3 rédigés individuellement — immobilier (36 simulateurs). */
export const immobilierHeadings: Record<string, SimulatorHeadings> = {
  "frais-de-notaire": {
    mainSection: "Comment estimer les frais de notaire à l'achat ?",
    definition: "Frais de notaire ou droits de mutation : de quoi s'agit-il ?",
    objectif: "Pourquoi les intégrer dès le début de votre budget d'acquisition ?",
    variables: "Prix d'achat, bien ancien ou neuf : quelles données saisir ?",
    formules: "Comment se décompose le calcul des droits de mutation ?",
    interpretation: "Que représente le montant affiché par le simulateur ?",
    limitesCalcul: "Pourquoi l'estimation peut varier d'un dossier à l'autre ?",
    maillage: "Quels simulateurs croiser pour budgétiser un achat immobilier ?",
    exempleSection: "Exemple de calcul des frais de notaire à l'achat",
    exempleDonnees: "Prix du bien et statut neuf ou ancien : que renseigner ?",
    exempleCalcul: "Étape par étape : comment le simulateur obtient le total",
    exempleResultat: "Où lire le détail des postes dans le résultat ?",
    exempleInterpretation: "Faut-il provisionner au-delà de l'estimation affichée ?",
    conseilsSection: "Anticiper les frais de notaire avant la signature",
    conseils: "Négociation du prix, prêt et calendrier : que prévoir ?",
    limites: "Points de vigilance sur cette estimation",
  },
  "taux-endettement": {
    mainSection: "Comment calculer son taux d'endettement ?",
    definition: "Le taux d'endettement bancaire, en bref",
    objectif: "Pourquoi les banques regardent ce ratio avant d'accorder un prêt ?",
    variables: "Revenus, crédits en cours : que mettre dans le calcul ?",
    formules: "Comment la banque calcule-t-elle le ratio d'endettement ?",
    interpretation: "Un ratio élevé ou bas : que ça change pour votre dossier",
    limitesCalcul: "Ce que ce ratio ne dit pas sur votre solvabilité",
    maillage: "Capacité d'emprunt, reste à vivre : quoi simuler ensuite ?",
    exempleSection: "Exemple de calcul du taux d'endettement d'un foyer",
    exempleDonnees: "Quels revenus et mensualités entrer dans le simulateur ?",
    exempleCalcul: "Du revenu net aux charges : le déroulé du calcul",
    exempleResultat: "Comment lire le pourcentage d'endettement obtenu ?",
    exempleInterpretation: "Peut-on emprunter malgré un ratio proche du plafond ?",
    conseilsSection: "Réduire son endettement avant de demander un prêt",
    conseils: "Rachat de crédit, durée de prêt et co-emprunteur : quelles pistes ?",
    limites: "Quand ce calcul ne suffit pas pour une réponse bancaire",
  },
  "cout-total-credit-immobilier": {
    mainSection: "Combien coûte réellement un crédit immobilier ?",
    definition: "Coût total du crédit : au-delà de la mensualité",
    objectif: "Pourquoi regarder le montant remboursé sur toute la durée ?",
    variables: "Capital, taux, durée, assurance : les paramètres clés",
    formules: "Intérêts, capital remboursé : comment le total se construit",
    interpretation: "Comparer deux offres de prêt grâce au coût global",
    limitesCalcul: "Frais annexes et taux révisables : ce qui n'est pas inclus",
    maillage: "Mensualité, assurance emprunteur : quels simulateurs associer ?",
    exempleSection: "Exemple d'estimation du coût total d'un prêt immobilier",
    exempleDonnees: "Montant emprunté, taux et durée : les saisies utiles",
    exempleCalcul: "Comment le simulateur additionne capital et intérêts",
    exempleResultat: "Où trouver le coût du crédit et la mensualité dans l'affichage",
    exempleInterpretation: "Un écart faible de taux peut-il coûter cher sur la durée ?",
    conseilsSection: "Limiter le coût de votre crédit immobilier",
    conseils: "Durée, apport et négociation du taux : par où commencer ?",
    limites: "Pourquoi le coût réel peut différer de la simulation",
  },
  "tableau-amortissement": {
    mainSection: "Comment lire un tableau d'amortissement de prêt ?",
    definition: "Tableau d'amortissement : capital, intérêts et solde restant",
    objectif: "Pourquoi suivre mois par mois la répartition de vos remboursements ?",
    variables: "Montant emprunté, taux, durée : ce qui alimente chaque ligne",
    formules: "Comment est calculée une ligne du tableau d'amortissement ?",
    interpretation: "Lire l'évolution du capital restant dû dans le temps",
    limitesCalcul: "Remboursements anticipés et révisions de taux : ce qui change le tableau",
    maillage: "Coût total du crédit, remboursement anticipé : quels outils utiles ?",
    exempleSection: "Exemple de tableau d'amortissement sur un prêt immobilier",
    exempleDonnees: "Capital, taux et durée : les données à renseigner",
    exempleCalcul: "Comment le simulateur génère les mensualités détaillées",
    exempleResultat: "Capital remboursé, intérêts payés : où les repérer ?",
    exempleInterpretation: "Pourquoi la part d'intérêts diminue au fil des échéances ?",
    conseilsSection: "Tirer parti d'un tableau d'amortissement",
    conseils: "Renégociation, remboursement anticipé : quand agir ?",
    limites: "Ce qu'un tableau simulé ne remplace pas dans un contrat réel",
  },
  "remboursement-anticipe": {
    mainSection: "Combien coûte un remboursement anticipé de crédit ?",
    definition: "Remboursement anticipé et indemnités (IRA) : les bases",
    objectif: "Pourquoi chiffrer les pénalités avant de solder votre prêt ?",
    variables: "Capital restant dû, taux de pénalité : les entrées du calcul",
    formules: "Comment sont calculées les indemnités de remboursement anticipé ?",
    interpretation: "IRA élevées ou faibles : que retenir pour votre décision ?",
    limitesCalcul: "Exonérations légales et clauses bancaires : ce qui modifie le montant",
    maillage: "Tableau d'amortissement, coût total du crédit : quoi vérifier avant ?",
    exempleSection: "Exemple de calcul des indemnités de remboursement anticipé",
    exempleDonnees: "Capital restant et conditions de pénalité : que saisir ?",
    exempleCalcul: "Comment le simulateur estime le coût des IRA",
    exempleResultat: "Où lire le montant des pénalités dans le résultat ?",
    exempleInterpretation: "Faut-il rembourser par avance malgré les indemnités ?",
    conseilsSection: "Préparer un remboursement anticipé de prêt",
    conseils: "Vente du bien, renégociation ou apport : quel timing choisir ?",
    limites: "Pourquoi le montant réel des IRA peut différer",
  },
  "pret-taux-zero-ptz": {
    mainSection: "Comment estimer son éligibilité au PTZ ?",
    definition: "Prêt à taux zéro (PTZ) : conditions et fonctionnement",
    objectif: "Pourquoi vérifier le PTZ avant de monter votre plan de financement ?",
    variables: "Revenus, zone, type de bien : les critères à renseigner",
    formules: "Comment le montant du prêt à taux zéro est-il déterminé ?",
    interpretation: "Que signifie le quota PTZ affiché pour votre projet ?",
    limitesCalcul: "Plafonds, quotités et évolutions réglementaires à connaître",
    maillage: "Capacité d'emprunt, frais de notaire : quels simulateurs en amont ?",
    exempleSection: "Exemple d'estimation du prêt à taux zéro pour un primo-accédant",
    exempleDonnees: "Revenus du foyer et prix du bien : les saisies nécessaires",
    exempleCalcul: "Comment le simulateur vérifie l'éligibilité et le quota",
    exempleResultat: "Où lire le montant PTZ et les conditions associées ?",
    exempleInterpretation: "Comment intégrer le PTZ dans le reste du financement ?",
    conseilsSection: "Obtenir et utiliser le prêt à taux zéro",
    conseils: "Primo-accédant, zone et type de logement : les points de vigilance",
    limites: "Ce que cette simulation ne garantit pas auprès de la banque",
  },
  "pret-relais": {
    mainSection: "Comment estimer un prêt relais immobilier ?",
    definition: "Prêt relais : financer l'achat en attendant la vente",
    objectif: "Pourquoi simuler un relais lors d'un achat avant revente ?",
    variables: "Valeur du bien à vendre, prix du nouveau bien : que renseigner ?",
    formules: "Comment sont calculés le montant et le coût d'un prêt relais ?",
    interpretation: "Que révèle la capacité de financement en mode relais ?",
    limitesCalcul: "Retard de vente, décote et durée : les risques hors simulateur",
    maillage: "Taux d'endettement, capacité d'emprunt : quoi croiser avant de signer ?",
    exempleSection: "Exemple de simulation d'un prêt relais entre deux transactions",
    exempleDonnees: "Valeur de revente et prix d'achat : les données clés",
    exempleCalcul: "Comment le simulateur dimensionne le montant du relais",
    exempleResultat: "Où lire le montant empruntable en attendant la vente ?",
    exempleInterpretation: "Que se passe-t-il si la vente du bien actuel traîne ?",
    conseilsSection: "Sécuriser un projet avec prêt relais",
    conseils: "Durée du relais, clause de révision et plan B : que prévoir ?",
    limites: "Pourquoi l'offre bancaire réelle peut diverger de l'estimation",
  },
  "rachat-credit-immobilier": {
    mainSection: "Le rachat de crédit immobilier est-il rentable ?",
    definition: "Rachat et regroupement de crédits : de quoi parle-t-on ?",
    objectif: "Pourquoi comparer l'ancien et le nouveau coût avant de regrouper ?",
    variables: "Crédits en cours, nouvelles conditions : les paramètres à saisir",
    formules: "Comment le simulateur mesure l'économie d'un rachat de crédit ?",
    interpretation: "Économies ou surcoût : comment lire la comparaison ?",
    limitesCalcul: "Frais de dossier, garanties et durée allongée : l'effet caché",
    maillage: "Taux d'endettement, coût total du crédit : quels outils avant un rachat ?",
    exempleSection: "Exemple de comparaison avant et après rachat de crédit",
    exempleDonnees: "Mensualités actuelles et nouveau taux : que renseigner ?",
    exempleCalcul: "Comment le simulateur oppose les deux scénarios",
    exempleResultat: "Où voir l'économie mensuelle ou le surcoût global ?",
    exempleInterpretation: "Dans quels cas le rachat n'est-il pas avantageux ?",
    conseilsSection: "Préparer un rachat de crédit immobilier",
    conseils: "Frais de dossier, assurance et durée : quels postes comparer ?",
    limites: "Ce que la simulation ne remplace pas dans une offre bancaire",
  },
  "assurance-emprunteur": {
    mainSection: "Combien coûte l'assurance emprunteur sur un prêt ?",
    definition: "Assurance emprunteur décès-invalidité : rôle et fonctionnement",
    objectif: "Pourquoi chiffrer le coût de l'assurance sur toute la durée du prêt ?",
    variables: "Capital emprunté, taux d'assurance, quotité : les entrées utiles",
    formules: "Comment est calculée la prime mensuelle d'assurance emprunteur ?",
    interpretation: "Lire le coût annuel et cumulé de l'assurance de prêt",
    limitesCalcul: "Tarification selon l'âge, la santé et le contrat groupe ou délégué",
    maillage: "Coût total du crédit, mensualité : quels simulateurs pour une vue globale ?",
    exempleSection: "Exemple de calcul du coût de l'assurance emprunteur",
    exempleDonnees: "Capital emprunté et taux d'assurance : que saisir ?",
    exempleCalcul: "Comment le simulateur calcule la prime sur la durée",
    exempleResultat: "Où trouver le budget mensuel et annuel d'assurance ?",
    exempleInterpretation: "Peut-on réduire ce coût grâce à la délégation d'assurance ?",
    conseilsSection: "Réduire le coût de l'assurance emprunteur",
    conseils: "Loi Lemoine, changement d'assureur et équivalence des garanties",
    limites: "Pourquoi votre devis réel peut différer de la simulation",
  },
  "frais-agence-immobiliere": {
    mainSection: "Combien coûtent les honoraires d'agence immobilière ?",
    definition: "Honoraires d'agence : commission, mandat et répartition",
    objectif: "Pourquoi intégrer les frais d'agence dans le budget d'acquisition ?",
    variables: "Prix du bien et taux d'honoraires : les données à renseigner",
    formules: "Comment sont calculés les honoraires d'une agence immobilière ?",
    interpretation: "Montant TTC, charge acquéreur ou vendeur : que lire ?",
    limitesCalcul: "Mandat exclusif, négociation et TVA : ce qui fait varier le total",
    maillage: "Frais de notaire, budget global d'achat : quels outils associer ?",
    exempleSection: "Exemple de calcul des honoraires d'agence immobilière",
    exempleDonnees: "Prix de vente et pourcentage d'honoraires : les saisies",
    exempleCalcul: "Comment le simulateur obtient le montant TTC des honoraires",
    exempleResultat: "Où lire le montant des honoraires dans le résultat ?",
    exempleInterpretation: "Honoraires à la charge de l'acheteur ou du vendeur ?",
    conseilsSection: "Comprendre et vérifier les honoraires d'agence",
    conseils: "Mandat, barème affiché et négociation : que contrôler avant signature ?",
    limites: "Ce que l'estimation ne couvre pas dans un mandat réel",
  },
  "frais-garantie-emprunt": {
    mainSection: "Combien coûtent les frais de garantie d'un prêt immobilier ?",
    definition: "Garantie de crédit : hypothèque, caution et autres options",
    objectif: "Pourquoi chiffrer la garantie dans le coût global du financement ?",
    variables: "Montant emprunté et type de garantie : que choisir dans le simulateur ?",
    formules: "Comment sont estimés les frais de caution ou d'hypothèque ?",
    interpretation: "Comparer le coût des différentes formes de garantie",
    limitesCalcul: "Frais de mainlevée, renouvellement et conditions bancaires",
    maillage: "Coût total du crédit, assurance emprunteur : quoi simuler en parallèle ?",
    exempleSection: "Exemple de calcul des frais de garantie de prêt",
    exempleDonnees: "Capital emprunté et type de garantie : les entrées du simulateur",
    exempleCalcul: "Comment le simulateur estime les frais selon la garantie choisie",
    exempleResultat: "Où lire le coût de la caution ou de l'hypothèque ?",
    exempleInterpretation: "Hypothèque ou caution : laquelle convient à votre profil ?",
    conseilsSection: "Choisir et optimiser la garantie de prêt",
    conseils: "Comparer banques, Crédit Logement et coût de mainlevée",
    limites: "Pourquoi les frais réels peuvent varier selon l'établissement",
  },
  "effort-epargne-immobilier": {
    mainSection: "Combien de temps pour épargner son apport immobilier ?",
    definition: "Effort d'épargne : constituer un apport pour acheter",
    objectif: "Pourquoi estimer la durée nécessaire avant de lancer votre projet ?",
    variables: "Apport visé, épargne mensuelle, rendement : les paramètres clés",
    formules: "Comment le simulateur projette l'accumulation de votre apport ?",
    interpretation: "Lire le délai pour atteindre l'objectif d'épargne fixé",
    limitesCalcul: "Inflation, imprévus et rendement variable : ce qui bouscule la projection",
    maillage: "Capacité d'emprunt, frais de notaire : quels simulateurs pour la suite ?",
    exempleSection: "Exemple de projection pour constituer un apport immobilier",
    exempleDonnees: "Objectif d'apport et capacité d'épargne mensuelle : que saisir ?",
    exempleCalcul: "Comment le simulateur avance mois par mois vers l'objectif",
    exempleResultat: "Où lire la durée estimée pour atteindre l'apport visé ?",
    exempleInterpretation: "Comment accélérer la constitution de votre apport ?",
    conseilsSection: "Constituer un apport pour acheter un bien",
    conseils: "Livret A, PEL, assurance-vie : quels supports selon votre horizon ?",
    limites: "Une projection d'épargne n'est pas un conseil en placement",
  },
  "impact-hausse-taux": {
    mainSection: "Quel impact d'une hausse de taux sur votre mensualité ?",
    definition: "Sensibilité d'un crédit aux variations de taux d'intérêt",
    objectif: "Pourquoi stresser votre prêt avant de vous engager sur la durée ?",
    variables: "Mensualité actuelle et hausse simulée : les données à entrer",
    formules: "Comment la mensualité est-elle recalculée après hausse de taux ?",
    interpretation: "Lire l'écart de mensualité et le surcoût sur la durée restante",
    limitesCalcul: "Taux fixe, variable ou capé : ce que change votre type de contrat",
    maillage: "Capacité d'emprunt, coût total du crédit : quels scénarios tester ?",
    exempleSection: "Exemple d'impact d'une hausse de taux sur un prêt immobilier",
    exempleDonnees: "Capital, taux initial et variation simulée : les saisies",
    exempleCalcul: "Comment le simulateur recalcule la mensualité après hausse",
    exempleResultat: "Où voir la nouvelle mensualité et le surcoût estimé ?",
    exempleInterpretation: "Comment se prémunir contre une remontée des taux ?",
    conseilsSection: "Faire face à une hausse des taux immobiliers",
    conseils: "Taux fixe, capé, durée plus courte : que privilégier ?",
    limites: "Un scénario de stress ne prédit pas l'évolution réelle des taux",
  },
  "credit-travaux": {
    mainSection: "Comment estimer la mensualité d'un crédit travaux ?",
    definition: "Crédit travaux : financer la rénovation d'un bien",
    objectif: "Pourquoi calculer le coût mensuel avant de lancer vos travaux ?",
    variables: "Montant emprunté, taux, durée : les conditions du prêt travaux",
    formules: "Comment est calculée la mensualité d'un prêt travaux ?",
    interpretation: "Lire la mensualité et le coût total du financement de rénovation",
    limitesCalcul: "Aides publiques, taux promotionnels et assurances non inclus",
    maillage: "Budget travaux, rentabilité après travaux : quels outils en amont ?",
    exempleSection: "Exemple de simulation d'un crédit travaux immobilier",
    exempleDonnees: "Budget travaux et conditions de prêt : que renseigner ?",
    exempleCalcul: "Comment le simulateur calcule mensualité et coût total",
    exempleResultat: "Où lire la mensualité et le montant total remboursé ?",
    exempleInterpretation: "Crédit travaux ou extension de prêt immobilier : que choisir ?",
    conseilsSection: "Financer des travaux immobiliers",
    conseils: "MaPrimeRénov', éco-PTZ et devis : quelles aides cumuler ?",
    limites: "Pourquoi l'offre bancaire réelle peut différer de la simulation",
  },
  "plus-value-immobiliere": {
    mainSection: "Comment calculer la plus-value immobilière à la revente ?",
    definition: "Plus-value immobilière : gain entre achat et vente",
    objectif: "Pourquoi estimer la plus-value avant de mettre un bien en vente ?",
    variables: "Prix d'achat, prix de vente, durée de détention : les entrées clés",
    formules: "Comment sont calculées la plus-value brute et l'impôt associé ?",
    interpretation: "Lire la plus-value nette après abattements pour durée de détention",
    limitesCalcul: "Résidence principale, travaux et frais : ce qui modifie l'impôt réel",
    maillage: "IFI, donation immobilière : quels simulateurs pour la suite du projet ?",
    exempleSection: "Exemple de calcul de plus-value à la revente d'un bien",
    exempleDonnees: "Prix d'achat, prix de vente et durée : les saisies utiles",
    exempleCalcul: "Comment le simulateur applique abattements et prélèvements",
    exempleResultat: "Où lire la plus-value nette et l'impôt estimé ?",
    exempleInterpretation: "Dans quels cas la plus-value immobilière est-elle exonérée ?",
    conseilsSection: "Optimiser la fiscalité à la revente d'un bien",
    conseils: "Durée de détention, travaux justifiés et résidence principale",
    limites: "Une estimation ne remplace pas le calcul fiscal définitif",
  },
  "rendement-locatif-brut": {
    mainSection: "Comment calculer le rendement locatif brut ?",
    definition: "Rendement locatif brut : loyer rapporté au prix d'achat",
    objectif: "Pourquoi calculer le brut avant d'aller plus loin dans l'analyse ?",
    variables: "Loyer annuel et coût total d'acquisition : que renseigner ?",
    formules: "Comment le simulateur calcule le rendement brut d'un bien locatif ?",
    interpretation: "Un rendement brut élevé ou faible : que retenir en première lecture ?",
    limitesCalcul: "Charges, vacance et fiscalité : pourquoi le brut ne suffit pas",
    maillage: "Rendement net, cash-flow : quels simulateurs pour affiner l'investissement ?",
    exempleSection: "Exemple de calcul du rendement locatif brut",
    exempleDonnees: "Loyer mensuel et prix d'achat total : les données à saisir",
    exempleCalcul: "Comment le simulateur obtient le ratio brut annuel",
    exempleResultat: "Où lire le pourcentage de rendement brut obtenu ?",
    exempleInterpretation: "Pourquoi le brut tend à surestimer la rentabilité réelle ?",
    conseilsSection: "Évaluer un rendement brut avant d'investir",
    conseils: "Ville, type de bien et loyer de marché : quels repères comparer ?",
    limites: "Le rendement brut seul ne dit pas si l'investissement est viable",
  },
  "rendement-locatif-net": {
    mainSection: "Comment calculer le rendement locatif net ?",
    definition: "Rendement locatif net : après charges et vacance locative",
    objectif: "Pourquoi intégrer charges et vacance au-delà du rendement brut ?",
    variables: "Loyers, charges annuelles, taux de vacance : les paramètres du net",
    formules: "Comment le simulateur calcule le rendement net après charges ?",
    interpretation: "Lire un rendement net plus proche de la réalité locative",
    limitesCalcul: "Impôt foncier, travaux et gestion locative : ce qui reste hors calcul",
    maillage: "Cash-flow, impôt sur les revenus fonciers : quoi simuler ensuite ?",
    exempleSection: "Exemple de calcul du rendement locatif net",
    exempleDonnees: "Loyer, charges et vacance locative : les saisies nécessaires",
    exempleCalcul: "Comment le simulateur déduit charges et périodes de vacance",
    exempleResultat: "Où lire le rendement net après déduction des charges ?",
    exempleInterpretation: "Un rendement net suffisant pour un cash-flow positif ?",
    conseilsSection: "Améliorer le rendement net d'un investissement locatif",
    conseils: "Charges de copropriété, taxe foncière et entretien : ne rien oublier",
    limites: "Pourquoi le net simulé peut différer de votre première année réelle",
  },
  "cash-flow-immobilier": {
    mainSection: "Comment calculer le cash-flow d'un investissement locatif ?",
    definition: "Cash-flow locatif : excédent ou déficit mensuel du bien",
    objectif: "Pourquoi savoir combien le bien vous laisse (ou vous coûte) chaque mois ?",
    variables: "Loyers, charges, crédit, fiscalité : les postes à renseigner",
    formules: "Comment le simulateur calcule le cash-flow mensuel locatif ?",
    interpretation: "Cash-flow positif ou négatif : que retenir pour votre stratégie ?",
    limitesCalcul: "Imprévus, vacance prolongée et révision de loyer : l'incertitude réelle",
    maillage: "Rendement net, LMNP, impôt foncier : quels outils pour compléter l'analyse ?",
    exempleSection: "Exemple de calcul du cash-flow d'un bien locatif financé",
    exempleDonnees: "Loyer, mensualité de crédit et charges : les entrées du simulateur",
    exempleCalcul: "Comment le simulateur calcule l'excédent ou le déficit mensuel",
    exempleResultat: "Où lire le cash-flow mensuel et annuel obtenu ?",
    exempleInterpretation: "Un cash-flow négatif est-il toujours un mauvais signe ?",
    conseilsSection: "Améliorer le cash-flow d'un investissement locatif",
    conseils: "Loyer, charges récupérables et conditions de financement : quoi ajuster ?",
    limites: "Un cash-flow simulé ne garantit pas la trésorerie réelle",
  },
  "rentabilite-lmnp": {
    mainSection: "Quelle rentabilité en location meublée (LMNP) ?",
    definition: "Location meublée non professionnelle (LMNP) : statut et fiscalité",
    objectif: "Pourquoi comparer la rentabilité LMNP au locatif nu ?",
    variables: "Loyers meublés, charges, amortissement : les données à saisir",
    formules: "Comment le simulateur calcule la rentabilité nette en LMNP ?",
    interpretation: "Lire le rendement net en tenant compte de la fiscalité meublée",
    limitesCalcul: "Seuil LMP, régime réel simplifié et évolution des loyers meublés",
    maillage: "Location meublée vs nue, cash-flow : quels simulateurs pour trancher ?",
    exempleSection: "Exemple de calcul de rentabilité en location meublée",
    exempleDonnees: "Loyer meublé et coût d'acquisition : les saisies utiles",
    exempleCalcul: "Comment le simulateur intègre charges et fiscalité LMNP",
    exempleResultat: "Où lire le rendement net en location meublée ?",
    exempleInterpretation: "LMNP ou location nue : quel régime selon votre profil ?",
    conseilsSection: "Réussir un investissement en LMNP",
    conseils: "Amortissement, micro-BIC et mobilier : les leviers du statut meublé",
    limites: "Ce que la simulation ne remplace pas chez un expert-comptable",
  },
  "budget-travaux": {
    mainSection: "Comment estimer le budget de travaux d'un bien ?",
    definition: "Budget travaux : chiffrer une rénovation avant d'acheter ou de lancer",
    objectif: "Pourquoi estimer les postes de travaux avant de vous engager ?",
    variables: "Postes de rénovation, surfaces, niveau de finition : que renseigner ?",
    formules: "Comment le simulateur totalise les postes de travaux ?",
    interpretation: "Lire un budget global et le détail par poste de rénovation",
    limitesCalcul: "Devis réels, malfaçons et aléas de chantier : l'écart possible",
    maillage: "Crédit travaux, rentabilité après travaux : quels outils pour la suite ?",
    exempleSection: "Exemple d'estimation du budget travaux d'un logement",
    exempleDonnees: "Travaux prévus et surfaces concernées : les saisies",
    exempleCalcul: "Comment le simulateur additionne chaque poste de rénovation",
    exempleResultat: "Où lire le budget total et la ventilation par poste ?",
    exempleInterpretation: "Comment prioriser les travaux selon le budget disponible ?",
    conseilsSection: "Maîtriser un budget travaux immobilier",
    conseils: "Marge de sécurité, devis comparés et aides à la rénovation",
    limites: "Une estimation en ligne ne remplace pas les devis d'artisans",
  },
  "rentabilite-apres-travaux": {
    mainSection: "Quelle rentabilité après travaux de rénovation ?",
    definition: "Rentabilité post-travaux : mesurer le gain après rénovation",
    objectif: "Pourquoi comparer le rendement avant et après travaux ?",
    variables: "Coût des travaux, loyer avant/après, prix d'achat : les entrées clés",
    formules: "Comment le simulateur calcule la rentabilité après rénovation ?",
    interpretation: "Lire le gain de rendement lié aux travaux réalisés",
    limitesCalcul: "Délais de location, surcoût de chantier et valeur vénale réelle",
    maillage: "Budget travaux, rendement net : quels simulateurs en amont et en aval ?",
    exempleSection: "Exemple de rentabilité locative après rénovation d'un bien",
    exempleDonnees: "Budget travaux et hausse de loyer attendue : que saisir ?",
    exempleCalcul: "Comment le simulateur compare la situation avant et après travaux",
    exempleResultat: "Où lire le rendement net après rénovation ?",
    exempleInterpretation: "Les travaux améliorent-ils vraiment la rentabilité du bien ?",
    conseilsSection: "Rentabiliser des travaux sur un bien locatif",
    conseils: "Quels travaux font le plus progresser le loyer et la valeur ?",
    limites: "Le surcoût réel des travaux peut modifier le calcul final",
  },
  "rentabilite-scpi": {
    mainSection: "Comment estimer la rentabilité d'une SCPI ?",
    definition: "SCPI : investir dans l'immobilier via des parts de société",
    objectif: "Pourquoi calculer le rendement avant de souscrire des parts de SCPI ?",
    variables: "Montant investi, taux de distribution, frais : les paramètres clés",
    formules: "Comment le simulateur calcule le rendement d'une SCPI ?",
    interpretation: "Lire le taux de distribution net après frais de souscription",
    limitesCalcul: "Vacance des actifs, revalorisation des parts et fiscalité personnelle",
    maillage: "Rendement locatif direct, IFI : quoi comparer avec la SCPI ?",
    exempleSection: "Exemple de calcul de rendement sur un investissement SCPI",
    exempleDonnees: "Capital investi, TD et frais : les saisies du simulateur",
    exempleCalcul: "Comment le simulateur calcule le rendement net SCPI",
    exempleResultat: "Où lire le revenu annuel estimé et le rendement net ?",
    exempleInterpretation: "SCPI ou immobilier direct : quels critères comparer ?",
    conseilsSection: "Investir en SCPI avec lucidité",
    conseils: "Frais, délai de jouissance et diversification : les points de vigilance",
    limites: "Les performances passées ne garantissent pas les revenus futurs",
  },
  "rentabilite-location-courte-duree": {
    mainSection: "Quelle rentabilité en location courte durée ?",
    definition: "Location meublée de courte durée : fonctionnement et revenus",
    objectif: "Pourquoi comparer la LCD au bail long terme avant de vous lancer ?",
    variables: "Tarif par nuit, taux d'occupation, charges : les données à saisir",
    formules: "Comment le simulateur calcule la rentabilité en location saisonnière ?",
    interpretation: "Lire le rendement net en tenant compte de l'occupation et des charges",
    limitesCalcul: "Réglementation locale, saisonnalité et coût du ménage",
    maillage: "LMNP, colocation, rendement net : quels régimes locatifs comparer ?",
    exempleSection: "Exemple de rentabilité en location courte durée",
    exempleDonnees: "Prix par nuit et taux d'occupation : les saisies nécessaires",
    exempleCalcul: "Comment le simulateur annualise les revenus de location saisonnière",
    exempleResultat: "Où lire le rendement net en location courte durée ?",
    exempleInterpretation: "La LCD est-elle plus rentable qu'un bail classique longue durée ?",
    conseilsSection: "Réussir en location courte durée",
    conseils: "Réglementation, ménage, conciergerie et vacance : que prévoir ?",
    limites: "Un scénario optimiste peut masquer la saisonnalité réelle",
  },
  "colocation-rentabilite": {
    mainSection: "Quelle rentabilité en colocation immobilière ?",
    definition: "Colocation : louer un bien chambre par chambre",
    objectif: "Pourquoi comparer colocation et location classique sur un même bien ?",
    variables: "Loyer par chambre, nombre de colocataires, charges : les entrées",
    formules: "Comment le simulateur calcule la rentabilité en colocation ?",
    interpretation: "Lire le rendement net d'une colocation face à un bail unique",
    limitesCalcul: "Turnover, mobilier, gestion accrue et cadre juridique",
    maillage: "Rendement net, charges récupérables : quels outils pour affiner ?",
    exempleSection: "Exemple de rentabilité d'un bien loué en colocation",
    exempleDonnees: "Loyer par chambre et charges communes : que renseigner ?",
    exempleCalcul: "Comment le simulateur totalise les loyers de colocation",
    exempleResultat: "Où lire le rendement net en colocation ?",
    exempleInterpretation: "Colocation : plus rentable mais plus exigeante à gérer ?",
    conseilsSection: "Investir et gérer un bien en colocation",
    conseils: "Bail colocation, mobilier et rotation des locataires : que prévoir ?",
    limites: "La rentabilité simulée ne couvre pas tout le temps de gestion",
  },
  "impot-revenus-fonciers": {
    mainSection: "Comment estimer l'impôt sur les revenus fonciers ?",
    definition: "Revenus fonciers : fiscalité des loyers en location nue",
    objectif: "Pourquoi anticiper l'impôt sur vos loyers avant la déclaration ?",
    variables: "Loyers bruts, charges déductibles, régime fiscal : les saisies",
    formules: "Comment le simulateur calcule l'impôt en micro-foncier ou au réel ?",
    interpretation: "Lire l'impôt estimé selon le régime choisi",
    limitesCalcul: "Déficit foncier, changement de régime et TMI personnelle",
    maillage: "Déficit foncier, taxe foncière, rendement net : quels outils associer ?",
    exempleSection: "Exemple de calcul de l'impôt sur les revenus fonciers",
    exempleDonnees: "Loyers perçus et charges déductibles : les données à entrer",
    exempleCalcul: "Comment le simulateur applique micro-foncier ou régime réel",
    exempleResultat: "Où lire l'impôt sur le revenu lié à vos loyers ?",
    exempleInterpretation: "Micro-foncier ou régime réel : lequel choisir pour votre bien ?",
    conseilsSection: "Optimiser la fiscalité de vos revenus fonciers",
    conseils: "Charges déductibles, travaux et option pour le régime réel",
    limites: "Une simulation ne remplace pas la liasse fiscale définitive",
  },
  "taxe-fonciere": {
    mainSection: "Comment estimer la taxe foncière d'un bien ?",
    definition: "Taxe foncière sur les propriétés bâties : bases et taux",
    objectif: "Pourquoi anticiper la taxe foncière dans un budget locatif ou résidentiel ?",
    variables: "Valeur locative cadastrale et taux communal : les entrées du calcul",
    formules: "Comment le simulateur calcule la taxe foncière annuelle ?",
    interpretation: "Lire le montant annuel estimé et son poids dans vos charges",
    limitesCalcul: "Révisions cadastrales, exonérations et évolution des taux locaux",
    maillage: "Rendement net, charges récupérables : quels simulateurs pour le budget locatif ?",
    exempleSection: "Exemple d'estimation de la taxe foncière d'un logement",
    exempleDonnees: "Base cadastrale et taux applicables : que saisir ?",
    exempleCalcul: "Comment le simulateur applique les taux locaux à la base",
    exempleResultat: "Où lire le montant annuel de taxe foncière estimé ?",
    exempleInterpretation: "Comment la taxe foncière pèse sur le rendement net locatif ?",
    conseilsSection: "Comprendre et anticiper sa taxe foncière",
    conseils: "Exonérations temporaires, dégrèvements et recours possible",
    limites: "L'avis d'imposition réel peut différer selon la commune",
  },
  "deficit-foncier": {
    mainSection: "Comment calculer et imputer un déficit foncier ?",
    definition: "Déficit foncier : quand les charges dépassent les loyers",
    objectif: "Pourquoi estimer l'avantage fiscal d'un déficit foncier ?",
    variables: "Loyers, charges courantes et travaux déductibles : les saisies",
    formules: "Comment le simulateur calcule le déficit foncier imputable ?",
    interpretation: "Lire l'économie d'impôt générée par le déficit foncier",
    limitesCalcul: "Plafond d'imputation sur le revenu global et report du solde",
    maillage: "Impôt fonciers, budget travaux : quels simulateurs en amont ?",
    exempleSection: "Exemple de calcul du déficit foncier après travaux",
    exempleDonnees: "Loyers perçus et travaux déductibles : les données à renseigner",
    exempleCalcul: "Comment le simulateur calcule le déficit imputable",
    exempleResultat: "Où lire la réduction d'impôt estimée ?",
    exempleInterpretation: "Comment imputer le déficit sur le revenu global ?",
    conseilsSection: "Optimiser le déficit foncier en location nue",
    conseils: "Quels travaux ouvrent droit au déficit foncier ?",
    limites: "Les règles d'imputation peuvent évoluer selon votre situation",
  },
  "donation-succession-immobiliere": {
    mainSection: "Combien coûtent les droits de donation ou succession immobilière ?",
    definition: "Droits de mutation à titre gratuit : donation et succession",
    objectif: "Pourquoi estimer la fiscalité avant de transmettre un bien ?",
    variables: "Valeur du bien, lien de parenté, abattements : les entrées clés",
    formules: "Comment sont calculés les droits de donation ou de succession ?",
    interpretation: "Lire le montant de droits selon le barème et les abattements",
    limitesCalcul: "Démembrement, biens multiples et évolutions législatives",
    maillage: "IFI, plus-value immobilière : quels outils pour une transmission globale ?",
    exempleSection: "Exemple de calcul des droits sur la transmission d'un bien",
    exempleDonnees: "Valeur du bien et lien entre donateur et bénéficiaire : les saisies",
    exempleCalcul: "Comment le simulateur applique barème et abattements",
    exempleResultat: "Où lire le montant de droits estimé pour la transmission ?",
    exempleInterpretation: "Donation ou succession : quelle stratégie selon votre situation ?",
    conseilsSection: "Transmettre un bien immobilier en limitant la fiscalité",
    conseils: "Donations entre vifs, démembrement et pacte Dutreil : que comparer ?",
    limites: "Un notaire reste indispensable pour sécuriser la transmission",
  },
  "location-meublee-vs-nue": {
    mainSection: "Location meublée ou nue : quelle rentabilité comparer ?",
    definition: "Quelle différence entre location meublée et location nue ?",
    objectif: "Pourquoi comparer les deux régimes avant de choisir votre stratégie ?",
    variables: "Loyers, charges et fiscalité pour chaque régime : les saisies",
    formules: "Quels rendements le simulateur oppose entre meublé et nu ?",
    interpretation: "Lire l'écart de rentabilité nette entre les deux régimes",
    limitesCalcul: "Gestion, turnover meublé et évolution réglementaire du nu",
    maillage: "LMNP, impôt fonciers, cash-flow : quels simulateurs pour approfondir ?",
    exempleSection: "Exemple comparatif location meublée et location nue",
    exempleDonnees: "Loyers meublé et nu sur un même bien : que renseigner ?",
    exempleCalcul: "Comment le simulateur compare les deux scénarios côte à côte",
    exempleResultat: "Où voir quel régime ressort le plus rentable net d'impôt ?",
    exempleInterpretation: "Meublé ou nu : quel choix selon votre profil fiscal ?",
    conseilsSection: "Choisir entre location meublée et location nue",
    conseils: "LMNP, micro-BIC, Pinel et contraintes de gestion : les critères de choix",
    limites: "Une comparaison simplifiée ne couvre pas toute la complexité fiscale",
  },
  "ifi-impot-fortune-immobiliere": {
    mainSection: "Comment estimer l'IFI sur son patrimoine immobilier ?",
    definition: "IFI : impôt sur la fortune immobilière, seuil et barème",
    objectif: "Pourquoi calculer l'IFI avant la déclaration annuelle ?",
    variables: "Valeur nette du patrimoine immobilier taxable : que renseigner ?",
    formules: "Comment le simulateur applique le barème progressif de l'IFI ?",
    interpretation: "Lire le montant d'IFI selon la valeur nette déclarée",
    limitesCalcul: "Décote résidence principale, dettes et biens exonérés",
    maillage: "Plus-value, donation immobilière : quels outils pour une vision patrimoniale ?",
    exempleSection: "Exemple de calcul de l'IFI sur un patrimoine immobilier",
    exempleDonnees: "Valeur des biens immobiliers et dettes : les saisies utiles",
    exempleCalcul: "Comment le simulateur applique le barème IFI tranche par tranche",
    exempleResultat: "Où lire le montant d'IFI estimé pour votre patrimoine ?",
    exempleInterpretation: "Quelles exonérations et décotes intégrer dans le calcul ?",
    conseilsSection: "Optimiser l'IFI sur son patrimoine immobilier",
    conseils: "Résidence principale, dettes admissibles et structures de détention",
    limites: "L'IFI réel dépend de votre déclaration et de votre situation familiale",
  },
  "revision-loyer-irl": {
    mainSection: "Comment calculer une révision de loyer selon l'IRL ?",
    definition: "Révision annuelle du loyer : indice IRL et clause du bail",
    objectif: "Pourquoi vérifier l'augmentation légale avant d'appliquer ou de contester ?",
    variables: "Loyer actuel, trimestre IRL de référence et nouveau : les saisies",
    formules: "Comment est calculée la hausse de loyer selon l'IRL ?",
    interpretation: "Lire le nouveau loyer après révision indexée sur l'IRL",
    limitesCalcul: "Plafonnement en zone tendue, bail récent et erreur d'indice",
    maillage: "Encadrement des loyers, loyer charges comprises : quoi vérifier en parallèle ?",
    exempleSection: "Exemple de révision de loyer selon l'indice IRL",
    exempleDonnees: "Loyer en cours et indices IRL : les données à renseigner",
    exempleCalcul: "Comment le simulateur applique la formule de révision IRL",
    exempleResultat: "Où lire le nouveau loyer après révision annuelle ?",
    exempleInterpretation: "Peut-on appliquer une hausse supérieure à l'IRL ?",
    conseilsSection: "Réviser un loyer en bail d'habitation vide",
    conseils: "Notification au locataire, clause du bail et plafonds en zone tendue",
    limites: "Une révision mal calculée peut être contestée par le locataire",
  },
  "encadrement-loyers": {
    mainSection: "Mon loyer respecte-t-il l'encadrement des loyers ?",
    definition: "Encadrement des loyers en zone tendue : plafonds et références",
    objectif: "Pourquoi vérifier le loyer de référence avant de signer un bail ?",
    variables: "Loyer demandé, loyer de référence, complément de loyer : les entrées",
    formules: "Comment le simulateur contrôle le respect du plafond légal ?",
    interpretation: "Lire si le loyer demandé dépasse le plafond autorisé",
    limitesCalcul: "Observatoires locaux, DPE récent et évolution des plafonds",
    maillage: "Révision IRL, loyer charges comprises : quels outils pour le locataire ?",
    exempleSection: "Exemple de contrôle du loyer en zone d'encadrement",
    exempleDonnees: "Loyer proposé, référence et complément : les saisies",
    exempleCalcul: "Comment le simulateur compare loyer demandé et plafond",
    exempleResultat: "Où voir si le loyer est conforme au plafond légal ?",
    exempleInterpretation: "Complément de loyer : dans quels cas est-il justifié ?",
    conseilsSection: "Encadrement des loyers : conseils locataires et bailleurs",
    conseils: "Observatoire local, DPE et relocation : que vérifier avant signature ?",
    limites: "Les plafonds varient selon la commune et l'actualisation locale",
  },
  "depot-garantie-locatif": {
    mainSection: "Quel montant maximum pour le dépôt de garantie ?",
    definition: "Dépôt de garantie locatif : règles et plafonds légaux",
    objectif: "Pourquoi vérifier le plafond avant de verser ou d'exiger un dépôt ?",
    variables: "Loyer hors charges et type de bail : vide ou meublé ?",
    formules: "Comment le simulateur calcule le plafond du dépôt de garantie ?",
    interpretation: "Lire le montant maximal autorisé pour le dépôt",
    limitesCalcul: "Caution solidaire, colocation et restitution partielle",
    maillage: "Loyer charges comprises, charges récupérables : quoi simuler avec le bail ?",
    exempleSection: "Exemple de calcul du plafond du dépôt de garantie",
    exempleDonnees: "Loyer mensuel hors charges et type de location : les saisies",
    exempleCalcul: "Comment le simulateur applique les plafonds légaux",
    exempleResultat: "Où lire le dépôt de garantie maximum exigible ?",
    exempleInterpretation: "Restitution du dépôt : quels délais et retenues possibles ?",
    conseilsSection: "Dépôt de garantie : bonnes pratiques locatives",
    conseils: "État des lieux, caution solidaire et preuve de paiement",
    limites: "Les litiges sur la restitution échappent au calcul du plafond",
  },
  "charges-recuperables-locataire": {
    mainSection: "Quelles charges locatives peut-on récupérer sur le locataire ?",
    definition: "Charges récupérables : ce que le locataire peut être amené à payer",
    objectif: "Pourquoi distinguer charges récupérables et non récupérables ?",
    variables: "Charges de copropriété, provisions et quote-part : les saisies",
    formules: "Comment le simulateur calcule la quote-part locataire ?",
    interpretation: "Lire le montant récupérable sur le locataire",
    limitesCalcul: "Décret des charges, forfait et régularisation annuelle",
    maillage: "Loyer charges comprises, taxe foncière : quels outils pour le bail complet ?",
    exempleSection: "Exemple de répartition des charges récupérables locatives",
    exempleDonnees: "Charges annuelles et quote-part locataire : que renseigner ?",
    exempleCalcul: "Comment le simulateur ventile les charges récupérables",
    exempleResultat: "Où lire le montant mensuel de charges pour le locataire ?",
    exempleInterpretation: "Régularisation annuelle des charges : comment ça fonctionne ?",
    conseilsSection: "Charges locatives : conseils pour bailleurs et locataires",
    conseils: "Décret des charges, forfait et provision : quel mode choisir ?",
    limites: "Une répartition simulée ne remplace pas la régularisation réelle",
  },
  "revision-loyer-commercial": {
    mainSection: "Comment réviser un loyer commercial (ILC ou ILAT) ?",
    definition: "Révision de loyer en bail commercial : indices ILC et ILAT",
    objectif: "Pourquoi calculer la nouvelle redevance selon l'indice du bail ?",
    variables: "Loyer actuel, indice de base et indice en cours : les saisies",
    formules: "Comment est calculée la révision ILC ou ILAT ?",
    interpretation: "Lire le loyer commercial révisé selon la clause d'indexation",
    limitesCalcul: "Clause triennale, plafonnement et renégociation du bail",
    maillage: "Encadrement des loyers résidentiels : quelle différence avec le commercial ?",
    exempleSection: "Exemple de révision de loyer sur un bail commercial",
    exempleDonnees: "Loyer en cours et indices ILC ou ILAT : les données à entrer",
    exempleCalcul: "Comment le simulateur applique la formule d'indexation",
    exempleResultat: "Où lire le nouveau loyer commercial après révision ?",
    exempleInterpretation: "ILC ou ILAT : quel indice selon votre bail ?",
    conseilsSection: "Révision de loyer commercial : conseils pratiques",
    conseils: "Clause d'indexation, révision triennale et renégociation",
    limites: "Le bail signé prime sur toute simulation générique",
  },
  "loyer-charges-comprises": {
    mainSection: "Comment calculer un loyer charges comprises (CC) ?",
    definition: "Loyer charges comprises : loyer HC plus provisions de charges",
    objectif: "Pourquoi convertir loyer HC en loyer CC, ou l'inverse ?",
    variables: "Loyer hors charges et montant des provisions : les entrées",
    formules: "Comment le simulateur calcule le loyer toutes charges comprises ?",
    interpretation: "Lire le loyer CC affichable au locataire",
    limitesCalcul: "Régularisation annuelle et charges non incluses dans le forfait",
    maillage: "Charges récupérables, encadrement des loyers : quoi vérifier sur l'annonce ?",
    exempleSection: "Exemple de conversion d'un loyer hors charges en loyer CC",
    exempleDonnees: "Loyer hors charges et provision mensuelle : les saisies",
    exempleCalcul: "Comment le simulateur additionne loyer et charges provisionnées",
    exempleResultat: "Où lire le loyer charges comprises pour le locataire ?",
    exempleInterpretation: "Loyer CC en annonce : que vérifier avant de signer le bail ?",
    conseilsSection: "Lire une annonce locative avec un loyer CC",
    conseils: "Charges, dépôt de garantie et encadrement : que comparer entre annonces ?",
    limites: "Le loyer CC affiché peut différer après régularisation des charges",
  },
};
