import type { SimulatorHeadings } from "./types";

/** Titres H2/H3 rédigés individuellement — quotidien (10 simulateurs). */
export const quotidienHeadings: Record<string, SimulatorHeadings> = {
  "calculateur-tva": {
    mainSection: "Passer du HT au TTC (et inversement)",
    definition: "La TVA en bref",
    objectif: "Convertir un montant hors ou toutes taxes comprises",
    variables: "Montant et taux de TVA applicable",
    formules: "Calcul de la TVA sur un montant",
    interpretation: "Lire les montants HT, TVA et TTC",
    limitesCalcul: "Taux spéciaux et cas particuliers non couverts",
    maillage: "Calculateurs complémentaires en gestion",
    exempleSection: "Exemple de conversion HT vers TTC",
    exempleDonnees: "Montant et taux à saisir",
    exempleCalcul: "Détail du calcul dans le simulateur",
    exempleResultat: "Les trois montants obtenus",
    exempleInterpretation: "TVA collectée et déductible en professionnel",
    conseilsSection: "Choisir le bon taux de TVA",
    conseils: "Taux réduits, autoliquidation et franchise en base",
    limites: "Un calculateur général, pas un outil comptable",
  },
  "calculateur-pourcentage": {
    mainSection: "Calculer X % d'une somme",
    definition: "Le pourcentage d'une quantité",
    objectif: "Obtenir une part ou une variation en pourcentage",
    variables: "Valeur de base et taux à appliquer",
    formules: "Formule du pourcentage appliquée",
    interpretation: "Lire le résultat obtenu",
    limitesCalcul: "Arrondis et cumuls de remises",
    maillage: "Outils de calcul du quotidien",
    exempleSection: "Exemple avec une remise en pourcentage",
    exempleDonnees: "Valeur et pourcentage à renseigner",
    exempleCalcul: "Application du taux dans le simulateur",
    exempleResultat: "Le montant correspondant au pourcentage",
    exempleInterpretation: "Pourcentage, points et variation relative",
    conseilsSection: "Éviter les erreurs courantes de pourcentage",
    conseils: "Remises cumulées et montants TTC inclus",
    limites: "Calculs simples, sans règles métier spécifiques",
  },
  "regle-de-trois": {
    mainSection: "Résoudre une règle de trois",
    definition: "Proportionnalité entre quatre grandeurs",
    objectif: "Trouver une valeur inconnue à partir de trois autres",
    variables: "Les trois valeurs connues et l'inconnue",
    formules: "Produit en croix et résolution",
    interpretation: "Vérifier le résultat obtenu",
    limitesCalcul: "Proportionnalité directe uniquement",
    maillage: "Calculateurs mathématiques complémentaires",
    exempleSection: "Exemple de proportionnalité directe",
    exempleDonnees: "Les grandeurs à renseigner",
    exempleCalcul: "Résolution pas à pas dans le simulateur",
    exempleResultat: "La quatrième valeur calculée",
    exempleInterpretation: "Contrôler le résultat avec le produit en croix",
    conseilsSection: "Bien utiliser la règle de trois",
    conseils: "Proportionnalité directe ou inverse : bien distinguer",
    limites: "Cas simples, sans contexte métier complexe",
  },
  "calculateur-age": {
    mainSection: "Connaître son âge exact en années, mois et jours",
    definition: "L'âge chronologique précis",
    objectif: "Calculer un âge à partir d'une date de naissance",
    variables: "Date de naissance et date de référence",
    formules: "Comptage en années, mois et jours",
    interpretation: "Lire l'âge affiché",
    limitesCalcul: "Fuseaux horaires et dates limites",
    maillage: "Outils de calcul temporel",
    exempleSection: "Exemple avec une date de naissance",
    exempleDonnees: "Quelle date saisir",
    exempleCalcul: "Décompte des années et jours écoulés",
    exempleResultat: "L'âge exact au jour près",
    exempleInterpretation: "Anniversaire, majorité et dates légales",
    conseilsSection: "Calculs courants liés à l'âge",
    conseils: "Fuseaux horaires et références légales",
    limites: "Calcul calendaire, sans valeur juridique autonome",
  },
  "calculateur-pourboire": {
    mainSection: "Calculer le pourboire au restaurant",
    definition: "Le pourboire sur une addition",
    objectif: "Estimer la somme à laisser selon le service",
    variables: "Montant de l'addition et pourcentage souhaité",
    formules: "Pourboire appliqué sur le total",
    interpretation: "Lire le pourboire et le total à régler",
    limitesCalcul: "Usages variables selon les pays",
    maillage: "Outils pour sorties et repas",
    exempleSection: "Exemple après un repas au restaurant",
    exempleDonnees: "Montant et taux de pourboire à indiquer",
    exempleCalcul: "Calcul du pourboire et du total",
    exempleResultat: "La somme à laisser pour un service satisfaisant",
    exempleInterpretation: "Habitudes en France et à l'étranger",
    conseilsSection: "Laisser un pourboire avec discernement",
    conseils: "Service compris, espèces ou carte",
    limites: "Un repère pratique, pas une obligation",
  },
  "partage-facture": {
    mainSection: "Partager une addition entre plusieurs",
    definition: "Répartir une note de façon équitable",
    objectif: "Savoir combien chacun doit payer",
    variables: "Montant total, nombre de convives et pourboire",
    formules: "Division de la note par personne",
    interpretation: "Lire la part individuelle",
    limitesCalcul: "Partage égal, sans consommation différenciée",
    maillage: "Calculateurs pour sorties entre amis",
    exempleSection: "Exemple de repas entre plusieurs convives",
    exempleDonnees: "Total, nombre de personnes et pourboire",
    exempleCalcul: "Répartition dans le simulateur",
    exempleResultat: "Le montant par personne",
    exempleInterpretation: "Partage égal ou au prorata de chaque consommation",
    conseilsSection: "Partager une note sans prise de tête",
    conseils: "Applications de paiement et arrondis pratiques",
    limites: "Répartition simple, sans gestion des extras individuels",
  },
  "convertisseur-devises": {
    mainSection: "Convertir une somme d'une devise à une autre",
    definition: "Le taux de change entre deux monnaies",
    objectif: "Obtenir l'équivalent d'un montant dans une autre devise",
    variables: "Montant, devise source et devise cible",
    formules: "Application du taux de change",
    interpretation: "Lire le montant converti",
    limitesCalcul: "Taux indicatif, frais bancaires non inclus",
    maillage: "Outils financiers du quotidien",
    exempleSection: "Exemple de conversion entre deux devises",
    exempleDonnees: "Montant et taux à renseigner",
    exempleCalcul: "Conversion dans le simulateur",
    exempleResultat: "Le montant dans la devise cible",
    exempleInterpretation: "Taux indicatif versus taux appliqué par la banque",
    conseilsSection: "Changer des devises au meilleur moment",
    conseils: "Frais de change, commission et date du taux",
    limites: "Conversion théorique, sans frais réels",
  },
  "convertisseur-heures-minutes": {
    mainSection: "Convertir heures, minutes et format décimal",
    definition: "Passer d'un format horaire à un autre",
    objectif: "Transformer une durée selon le format utile",
    variables: "Durée en heures, minutes ou décimal",
    formules: "Conversion entre les formats",
    interpretation: "Lire la durée dans le format choisi",
    limitesCalcul: "Arrondis sur les centièmes d'heure",
    maillage: "Outils de calcul temporel",
    exempleSection: "Exemple de conversion d'une durée",
    exempleDonnees: "La durée à convertir",
    exempleCalcul: "Transformation dans le simulateur",
    exempleResultat: "La durée en minutes et en heures décimales",
    exempleInterpretation: "Heures décimales en paie et feuilles de temps",
    conseilsSection: "Convertir des durées sans se tromper",
    conseils: "Centièmes d'heure, pauses et temps de travail",
    limites: "Conversion pure, sans règles de paie intégrées",
  },
  "vitesse-distance-temps": {
    mainSection: "Calculer vitesse, distance ou durée de trajet",
    definition: "La relation vitesse × temps = distance",
    objectif: "Estimer un temps de route ou une distance parcourue",
    variables: "Deux des trois grandeurs : vitesse, distance, durée",
    formules: "Formules du mouvement uniforme",
    interpretation: "Lire le temps ou la distance calculée",
    limitesCalcul: "Vitesse moyenne, trafic et pauses non inclus",
    maillage: "Outils de calcul pratiques",
    exempleSection: "Exemple de trajet sur autoroute",
    exempleDonnees: "Distance, vitesse ou temps à saisir",
    exempleCalcul: "Application de la formule dans le simulateur",
    exempleResultat: "La durée ou la distance obtenue",
    exempleInterpretation: "Intégrer pauses, trafic et vitesse réelle",
    conseilsSection: "Estimer un trajet de façon réaliste",
    conseils: "Limites de vitesse, péages et consommation",
    limites: "Calcul théorique, sans conditions de route",
  },
  "evolution-pourcentage": {
    mainSection: "Mesurer une hausse ou une baisse en pourcentage",
    definition: "Le taux d'évolution entre deux valeurs",
    objectif: "Quantifier une variation relative",
    variables: "Valeur initiale et valeur finale",
    formules: "Calcul du taux de variation",
    interpretation: "Lire la hausse ou la baisse en pourcentage",
    limitesCalcul: "Base nulle et variations successives",
    maillage: "Calculateurs de pourcentage complémentaires",
    exempleSection: "Exemple de variation entre deux montants",
    exempleDonnees: "Valeur de départ et valeur d'arrivée",
    exempleCalcul: "Calcul de la variation relative",
    exempleResultat: "Le pourcentage d'augmentation ou de baisse",
    exempleInterpretation: "Points de pourcentage et pourcentage relatif",
    conseilsSection: "Interpréter une évolution sans se tromper",
    conseils: "Inflation, base de calcul et arrondis",
    limites: "Variation simple entre deux points, sans historique",
  },
};
