import type { SimulatorHeadings } from "./types";

/** Titres H2/H3 rédigés individuellement — santé (10 simulateurs). */
export const santeHeadings: Record<string, SimulatorHeadings> = {
  "calculateur-imc": {
    mainSection: "Calculer son indice de masse corporelle",
    definition: "L'IMC, c'est quoi exactement ?",
    objectif: "Pourquoi se pencher sur son indice de masse corporelle",
    variables: "Poids et taille : les deux champs à renseigner",
    formules: "Poids divisé par la taille au carré",
    interpretation: "Où se situe votre résultat sur le barème OMS",
    limitesCalcul: "Quand l'IMC ne reflète pas la réalité",
    maillage: "Simulateurs à combiner avec l'IMC",
    exempleSection: "Exemple de calcul d'IMC pas à pas",
    exempleDonnees: "Quelles valeurs saisir dans le formulaire",
    exempleCalcul: "Comment le simulateur obtient le chiffre",
    exempleResultat: "Le résultat et la catégorie affichée",
    exempleInterpretation: "Normal, surpoids ou insuffisance : que retenir",
    conseilsSection: "Lire son IMC sans se faire de fausses idées",
    conseils: "Masse grasse, morphologie et suivi médical",
    limites: "Les limites de l'IMC comme indicateur",
  },
  "poids-ideal": {
    mainSection: "Estimer son poids idéal selon sa taille",
    definition: "Le poids idéal théorique, en deux mots",
    objectif: "Une fourchette de poids pour se situer",
    variables: "Taille, sexe et formule de référence",
    formules: "Comment la fourchette est établie",
    interpretation: "Que signifie le poids idéal affiché",
    limitesCalcul: "Pourquoi une fourchette ne suffit pas toujours",
    maillage: "Outils complémentaires au poids idéal",
    exempleSection: "Exemple d'estimation selon la morphologie",
    exempleDonnees: "Taille et sexe à indiquer",
    exempleCalcul: "Application des formules dans le simulateur",
    exempleResultat: "La fourchette de poids obtenue",
    exempleInterpretation: "Croiser poids idéal et IMC",
    conseilsSection: "Viser un poids compatible avec la santé",
    conseils: "Objectif réaliste, activité et alimentation",
    limites: "Ce que cette estimation ne prend pas en compte",
  },
  "calories-journalieres": {
    mainSection: "Estimer ses besoins caloriques quotidiens",
    definition: "Métabolisme de base et dépense totale",
    objectif: "Savoir combien de calories consommer par jour",
    variables: "Âge, sexe, poids, taille et niveau d'activité",
    formules: "Du BMR au TDEE : le calcul expliqué",
    interpretation: "Lire le nombre de kcal recommandé",
    limitesCalcul: "Une estimation, pas un bilan métabolique",
    maillage: "Simulateurs liés à l'alimentation",
    exempleSection: "Exemple pour un profil actif",
    exempleDonnees: "Les données anthropométriques à renseigner",
    exempleCalcul: "Calcul du métabolisme et de la dépense totale",
    exempleResultat: "Les kcal journalières pour maintenir son poids",
    exempleInterpretation: "Déficit ou surplus pour perdre ou prendre du poids",
    conseilsSection: "Ajuster son apport calorique au quotidien",
    conseils: "Macros, activité physique et régularité",
    limites: "Les imprécisions d'une estimation calorique",
  },
  "date-accouchement": {
    mainSection: "Estimer sa date d'accouchement prévue",
    definition: "La DPA, date repère de la grossesse",
    objectif: "Anticiper le terme à partir des dernières règles",
    variables: "La date des dernières règles (DDR)",
    formules: "La règle de Naegele appliquée",
    interpretation: "Que représente la date affichée",
    limitesCalcul: "Terme réel et cycles irréguliers",
    maillage: "Outils utiles pendant la grossesse",
    exempleSection: "Exemple à partir d'une date de règles",
    exempleDonnees: "Quelle DDR saisir",
    exempleCalcul: "Ajout des semaines d'aménorrhée dans le simulateur",
    exempleResultat: "La date d'accouchement prévue",
    exempleInterpretation: "Marge habituelle entre DPA et accouchement réel",
    conseilsSection: "Suivi de grossesse et dates clés",
    conseils: "Échographie, semaines d'aménorrhée et déclaration",
    limites: "Une estimation médicale à confirmer en consultation",
  },
  "calculateur-ovulation": {
    mainSection: "Repérer sa période fertile",
    definition: "Fenêtre de fertilité : de quoi parle-t-on",
    objectif: "Identifier les jours propices à la conception",
    variables: "Date des dernières règles et durée du cycle",
    formules: "Estimation de la date d'ovulation",
    interpretation: "Lire le calendrier fertile affiché",
    limitesCalcul: "Cycles variables et méthodes plus précises",
    maillage: "Simulateurs complémentaires à la fertilité",
    exempleSection: "Exemple avec un cycle régulier",
    exempleDonnees: "DDR et durée de cycle à indiquer",
    exempleCalcul: "Repérage de l'ovulation et des jours fertiles",
    exempleResultat: "Les jours à considérer comme fertiles",
    exempleInterpretation: "Tests d'ovulation et cycles irréguliers",
    conseilsSection: "Conception et connaissance du cycle",
    conseils: "Stress, contraception et régularité du cycle",
    limites: "Une estimation, pas un diagnostic de fertilité",
  },
  "hydratation-quotidienne": {
    mainSection: "Combien d'eau boire chaque jour",
    definition: "Les besoins quotidiens en hydratation",
    objectif: "Adapter sa consommation d'eau à son profil",
    variables: "Poids, activité physique et conditions climatiques",
    formules: "Comment la quantité journalière est estimée",
    interpretation: "Lire le volume d'eau recommandé",
    limitesCalcul: "Besoins individuels très variables",
    maillage: "Autres simulateurs bien-être",
    exempleSection: "Exemple avec activité modérée",
    exempleDonnees: "Poids et niveau d'activité à renseigner",
    exempleCalcul: "Estimation des litres par jour",
    exempleResultat: "Le volume d'eau conseillé",
    exempleInterpretation: "Eau pure, boissons et aliments hydratants",
    conseilsSection: "Bien s'hydrater au fil de la journée",
    conseils: "Signes de déshydratation et effort physique",
    limites: "Une recommandation générale, pas un avis médical",
  },
  "proteines-journalieres": {
    mainSection: "Calculer son apport protéique quotidien",
    definition: "Les protéines au quotidien : l'essentiel",
    objectif: "Adapter les grammes de protéines à son objectif",
    variables: "Poids, objectif sportif et niveau d'activité",
    formules: "Grammes par kilo de poids corporel",
    interpretation: "Lire la quantité de protéines recommandée",
    limitesCalcul: "Besoins très personnels selon la santé",
    maillage: "Simulateurs nutrition complémentaires",
    exempleSection: "Exemple en phase de prise de masse",
    exempleDonnees: "Poids et objectif à saisir",
    exempleCalcul: "Application du ratio g/kg dans le simulateur",
    exempleResultat: "Les grammes de protéines par jour",
    exempleInterpretation: "Répartir l'apport et choisir ses sources",
    conseilsSection: "Couvrir ses besoins en protéines",
    conseils: "Alimentation, compléments et fonction rénale",
    limites: "Une fourchette indicative, pas un plan nutritionnel",
  },
  "economies-arret-tabac": {
    mainSection: "Mesurer les économies après l'arrêt du tabac",
    definition: "L'argent économisé sans cigarettes",
    objectif: "Visualiser le gain financier du sevrage",
    variables: "Consommation quotidienne et prix du paquet",
    formules: "Projection mensuelle et annuelle",
    interpretation: "Lire les montants économisés",
    limitesCalcul: "Prix variables et consommation fluctuante",
    maillage: "Outils complémentaires au sevrage",
    exempleSection: "Exemple pour un fumeur régulier",
    exempleDonnees: "Nombre de paquets et tarif à indiquer",
    exempleCalcul: "Projection des économies dans le temps",
    exempleResultat: "Le total économisé sur un an",
    exempleInterpretation: "Économies, santé et accompagnement au sevrage",
    conseilsSection: "Arrêter de fumer : par où commencer",
    conseils: "Tabac Info Service, substituts et suivi",
    limites: "Une projection financière, pas un bilan de sevrage",
  },
  "unites-alcool": {
    mainSection: "Convertir ses verres en unités d'alcool",
    definition: "L'unité d'alcool, standard de référence",
    objectif: "Quantifier sa consommation en unités",
    variables: "Type de boisson, volume servi et degré",
    formules: "Du volume et du degré aux grammes d'alcool pur",
    interpretation: "Lire le nombre d'unités consommées",
    limitesCalcul: "Verres maison et cocktails : des approximations",
    maillage: "Simulateurs liés au mode de vie",
    exempleSection: "Exemple avec un verre de vin",
    exempleDonnees: "Volume et degré d'alcool à renseigner",
    exempleCalcul: "Conversion en unités dans le simulateur",
    exempleResultat: "Le nombre d'unités pour votre verre",
    exempleInterpretation: "Seuils repères de Santé publique France",
    conseilsSection: "Consommer avec modération",
    conseils: "Alternance avec l'eau, repas et conduite",
    limites: "Un outil de repère, pas un bilan de consommation",
  },
  "cycles-sommeil": {
    mainSection: "Trouver l'heure idéale pour se coucher",
    definition: "Les cycles de sommeil de 90 minutes",
    objectif: "Se réveiller entre deux cycles, pas au milieu",
    variables: "Heure de réveil souhaitée ou heure de coucher",
    formules: "Créneaux de coucher alignés sur les cycles",
    interpretation: "Choisir parmi les heures suggérées",
    limitesCalcul: "Endormissement variable d'une nuit à l'autre",
    maillage: "Outils complémentaires au repos",
    exempleSection: "Exemple pour un réveil matinal",
    exempleDonnees: "Heure de réveil ou de coucher à saisir",
    exempleCalcul: "Décompte des cycles de 90 minutes",
    exempleResultat: "Les heures de coucher pour plusieurs durées de sommeil",
    exempleInterpretation: "Prévoir la latence d'endormissement",
    conseilsSection: "Améliorer la qualité de son sommeil",
    conseils: "Hygiène du sommeil, écrans et siestes",
    limites: "Un guide pratique, pas un diagnostic du sommeil",
  },
};
