import type { SimulatorHeadings } from "./types";

/** Titres H2/H3 rédigés individuellement — travaux (10 simulateurs). */
export const travauxHeadings: Record<string, SimulatorHeadings> = {
  "quantite-peinture": {
    mainSection: "Combien de peinture acheter pour vos murs ?",
    definition: "Rendement d'une peinture : ce que dit l'étiquette du pot",
    objectif: "Éviter le surachat (ou la seconde course au magasin)",
    variables: "Surface à peindre, nombre de couches, rendement au m²",
    formules: "Comment le simulateur passe des m² aux litres nécessaires ?",
    interpretation: "La quantité estimée couvre-t-elle plafonds et retouches ?",
    limitesCalcul: "Pourquoi le rendement réel peut varier sur le chantier",
    maillage: "Peinture, surface de pièce, budget travaux : outils complémentaires",
    exempleSection: "Exemple de calcul de quantité de peinture pour un salon",
    exempleDonnees: "Surface des murs, hauteur sous plafond et nombre de couches",
    exempleCalcul: "Surface peignable puis conversion en litres",
    exempleResultat: "Le nombre de litres à prévoir à l'achat",
    exempleInterpretation: "Sous-couche, plafond et pertes à la louche : les marges utiles",
    conseilsSection: "Acheter la bonne quantité de peinture",
    conseils: "Finition mate ou satinée, dilution et format de pot : éviter le gaspillage",
    limites: "Ce que ce calcul de peinture ne peut pas anticiper",
  },
  "calcul-carrelage": {
    mainSection: "Combien de carreaux commander pour votre pièce ?",
    definition: "Surface à carreler : m² utiles et découpes à prévoir",
    objectif: "Commander assez de carrelage du premier coup",
    variables: "Surface, format du carreau, marge de casse",
    formules: "Comment le simulateur estime le nombre de carreaux ?",
    interpretation: "Votre commande inclut-elle assez de carreaux de réserve ?",
    limitesCalcul: "Les pièces atypiques que ce calcul simplifie",
    maillage: "Carrelage, mortier, budget travaux : simulateurs pour un même chantier",
    exempleSection: "Exemple de calcul de carrelage pour une salle de bain",
    exempleDonnees: "Surface au sol et dimensions du carreau choisi",
    exempleCalcul: "Surface carrelable, marge de casse et joints intégrés",
    exempleResultat: "Le nombre de carreaux à commander",
    exempleInterpretation: "Casse, découpes et colle : ce qu'il faut prévoir en plus",
    conseilsSection: "Bien acheter son carrelage",
    conseils: "Lot unique, largeur de joint et préparation du support : les points clés",
    limites: "Les limites d'une estimation sur une surface rectangulaire simple",
  },
  "volume-beton": {
    mainSection: "Quel volume de béton pour votre dalle ou fondation ?",
    definition: "Volume de béton en m³ : longueur × largeur × épaisseur",
    objectif: "Commander la bonne quantité avant le coulage",
    variables: "Longueur, largeur et épaisseur de l'ouvrage à couler",
    formules: "Comment le simulateur calcule le volume en mètres cubes ?",
    interpretation: "Votre commande tient-elle compte des pertes au coulage ?",
    limitesCalcul: "Formes complexes et terrains en pente : hors périmètre",
    maillage: "Béton, budget travaux, surface de pièce : outils pour préparer un chantier",
    exempleSection: "Exemple de calcul de volume de béton pour une dalle",
    exempleDonnees: "Dimensions de la dalle à couler",
    exempleCalcul: "Multiplication L × l × h pour obtenir les m³",
    exempleResultat: "Le volume de béton à commander",
    exempleInterpretation: "Pertes, pompage et fibrage : les marges à ajouter",
    conseilsSection: "Préparer un coulage de béton",
    conseils: "Dosage, cure et conditions météo : avant de lancer le camion toupie",
    limites: "Ce que cette estimation de volume ne remplace pas",
  },
  "surface-parquet": {
    mainSection: "Combien de parquet acheter pour vos pièces ?",
    definition: "Surface utile de parquet : m² au sol et marge de coupe",
    objectif: "Estimer les m² à commander avec une marge de sécurité",
    variables: "Surface des pièces et pourcentage de perte à la pose",
    formules: "Comment le simulateur calcule la surface de parquet nécessaire ?",
    interpretation: "Votre commande couvre-t-elle les découpes et chutes ?",
    limitesCalcul: "Pièces irrégulières et sens de pose : source d'écart",
    maillage: "Parquet, surface de pièce, budget travaux : simulateurs utiles",
    exempleSection: "Exemple de calcul de surface de parquet pour un appartement",
    exempleDonnees: "Liste des pièces et surface totale au sol",
    exempleCalcul: "Surface brute plus marge de coupe en pourcentage",
    exempleResultat: "Les m² de parquet à acheter",
    exempleInterpretation: "Sens de pose, plinthes et sous-couche : au-delà des m²",
    conseilsSection: "Choisir et poser son parquet",
    conseils: "Stratifié, massif ou contrecollé : impact sur les quantités et la pose",
    limites: "Les approximations de ce calcul de surface parquet",
  },
  "maprimerenov": {
    mainSection: "MaPrimeRénov' : quel montant pour vos travaux ?",
    definition: "MaPrimeRénov', l'aide publique à la rénovation énergétique",
    objectif: "Estimer l'aide avant de signer un devis de travaux",
    variables: "Revenus du foyer, type de travaux, gain énergétique visé",
    formules: "Comment le simulateur applique barèmes et plafonds MaPrimeRénov' ?",
    interpretation: "Le montant estimé correspond-il à votre profil et vos travaux ?",
    limitesCalcul: "Pourquoi cette simulation ne vaut pas décision d'Anah",
    maillage: "MaPrimeRénov', économies d'isolation, consommation énergétique : à croiser",
    exempleSection: "Exemple d'aide MaPrimeRénov' pour l'isolation des combles",
    exempleDonnees: "Revenus du foyer, travaux prévus et catégorie de revenus",
    exempleCalcul: "Application des barèmes selon le type de travaux",
    exempleResultat: "Le montant MaPrimeRénov' estimé pour votre projet",
    exempleInterpretation: "Cumul CEE, éco-PTZ et aides locales : ne pas compter deux fois",
    conseilsSection: "Obtenir MaPrimeRénov' sans mauvaise surprise",
    conseils: "Accompagnateur Rénov', DPE et devis RGE : les étapes à respecter",
    limites: "Les cas où cette estimation MaPrimeRénov' peut évoluer",
  },
  "estimation-consommation-energie": {
    mainSection: "Quelle consommation énergétique pour votre logement ?",
    definition: "Consommation annuelle en kWh : ce que mesure le DPE",
    objectif: "Anticiper la facture de chauffage et d'énergie",
    variables: "Surface, isolation, mode de chauffage, classe DPE",
    formules: "Comment le simulateur estime les kWh consommés par an ?",
    interpretation: "Votre logement est-il une passoire thermique ou bien classé ?",
    limitesCalcul: "Usages réels et météo : variables absentes du calcul",
    maillage: "Consommation, isolation, pompe à chaleur : simulateurs rénovation énergétique",
    exempleSection: "Exemple d'estimation de consommation pour une maison individuelle",
    exempleDonnees: "Surface habitable, énergie de chauffage et classe DPE",
    exempleCalcul: "Estimation des kWh annuels puis du coût énergétique",
    exempleResultat: "La facture énergétique annuelle estimée",
    exempleInterpretation: "Passoire thermique et travaux prioritaires : lire les résultats",
    conseilsSection: "Réduire la consommation énergétique de son logement",
    conseils: "Isolation, thermostat intelligent et ENR : par où commencer",
    limites: "Pourquoi cette estimation énergétique reste une fourchette",
  },
  "pompe-a-chaleur-economies": {
    mainSection: "Une pompe à chaleur, combien d'économies sur la facture ?",
    definition: "Économies d'une PAC : comparer deux modes de chauffage",
    objectif: "Mesurer la baisse de facture en remplaçant fioul, gaz ou électrique",
    variables: "Consommation actuelle, COP de la PAC, prix de l'énergie",
    formules: "Comment le simulateur compare les coûts de chauffage annuels ?",
    interpretation: "Les économies estimées justifient-elles l'investissement ?",
    limitesCalcul: "COP réel, isolation et climat local : sources d'écart",
    maillage: "PAC, consommation énergétique, MaPrimeRénov' : outils pour un projet complet",
    exempleSection: "Exemple d'économies en remplaçant une chaudière fioul par une PAC",
    exempleDonnees: "Consommation actuelle et COP de la pompe à chaleur envisagée",
    exempleCalcul: "Comparaison du coût annuel avant et après installation",
    exempleResultat: "L'économie annuelle estimée sur la facture de chauffage",
    exempleInterpretation: "Investissement, aides publiques et délai de retour : le tableau complet",
    conseilsSection: "Choisir et dimensionner une pompe à chaleur",
    conseils: "Air-eau, géothermie, puissance installée : les critères de choix",
    limites: "Ce que cette simulation d'économies PAC ne garantit pas",
  },
  "volume-surface-piece": {
    mainSection: "Surface et volume d'une pièce : comment les calculer ?",
    definition: "Volume cubique d'une pièce : à quoi sert le m³ ?",
    objectif: "Obtenir m² au sol et m³ pour clim, ventilation ou peinture",
    variables: "Longueur, largeur et hauteur sous plafond de la pièce",
    formules: "Comment le simulateur calcule surface au sol et volume ?",
    interpretation: "Quand utiliser les m² et quand passer aux m³ ?",
    limitesCalcul: "Pièces en L, combles et ouvertures : limites du modèle rectangulaire",
    maillage: "Surface de pièce, peinture, consommation énergétique : simulateurs liés",
    exempleSection: "Exemple de calcul de surface et volume pour une chambre",
    exempleDonnees: "Dimensions de la pièce (longueur, largeur, hauteur)",
    exempleCalcul: "Surface au sol puis multiplication par la hauteur",
    exempleResultat: "Les m² et m³ obtenus pour votre pièce",
    exempleInterpretation: "Clim, peinture, acoustique : quel indicateur pour quel usage",
    conseilsSection: "Mesurer une pièce correctement",
    conseils: "Ouvertures, pièces irrégulières et combles : astuces de mesure",
    limites: "Les cas où ce calcul simple ne suffit pas",
  },
  "quantite-mortier": {
    mainSection: "Combien de sacs de mortier ou de colle pour votre chantier ?",
    definition: "Consommation de mortier au m² : ce qu'indique la fiche produit",
    objectif: "Estimer le nombre de sacs avant de commencer la pose",
    variables: "Surface à traiter, épaisseur de joint, rendement du produit",
    formules: "Comment le simulateur convertit m² en sacs ou kilogrammes ?",
    interpretation: "Votre estimation inclut-elle une marge pour les pertes ?",
    limitesCalcul: "Supports irréguliers et gros format : consommation variable",
    maillage: "Mortier, carrelage, budget travaux : simulateurs pour la même pose",
    exempleSection: "Exemple de calcul de mortier pour une pose de carrelage",
    exempleDonnees: "Surface carrelée et consommation indiquée au m²",
    exempleCalcul: "Surface multipliée par la consommation, convertie en sacs",
    exempleResultat: "Le nombre de sacs de mortier ou colle à acheter",
    exempleInterpretation: "Colle vs mortier traditionnel, eau et pertes : les ajustements",
    conseilsSection: "Préparer mortier et colle sur le chantier",
    conseils: "Temps ouvrable, température et état du support : avant de mélanger",
    limites: "Les écarts possibles entre fiche technique et terrain",
  },
  "economies-isolation": {
    mainSection: "Isoler son logement : combien économiser sur la facture ?",
    definition: "Économies d'isolation : la baisse de consommation après travaux",
    objectif: "Estimer la réduction de facture de chauffage après isolation",
    variables: "Surface isolée, résistance thermique R, consommation avant travaux",
    formules: "Comment le simulateur estime la baisse de kWh consommés ?",
    interpretation: "Vos économies annuelles amortissent-elles le coût des travaux ?",
    limitesCalcul: "Ponts thermiques et comportement des occupants : non modélisés",
    maillage: "Isolation, MaPrimeRénov', consommation énergétique : le trio rénovation",
    exempleSection: "Exemple d'économies après isolation des combles perdus",
    exempleDonnees: "Surface isolée, résistance R de l'isolant et facture avant travaux",
    exempleCalcul: "Estimation de la baisse de kWh puis du gain en euros",
    exempleResultat: "L'économie annuelle sur la facture de chauffage",
    exempleInterpretation: "Retour sur investissement et cumul avec MaPrimeRénov' : le bilan",
    conseilsSection: "Isoler efficacement son logement",
    conseils: "Combles, murs et ponts thermiques : par où commencer les travaux",
    limites: "Pourquoi ces économies d'isolation restent une projection",
  },
};
