/**
 * Association slug → modules réglementaires (src/data/regulations/).
 * Centralisé pour éviter de modifier 100+ fichiers simulateur.
 */
export const SIMULATOR_REGULATION_IDS: Record<string, string[]> = {
  "capacite-emprunt": ["immobilier"],
  "rendement-locatif": ["fiscalite"],
  "mensualite-pret-immobilier": ["immobilier"],
  "frais-de-notaire": ["immobilier"],
  "taux-endettement": ["immobilier"],
  "cout-total-credit-immobilier": ["immobilier"],
  "tableau-amortissement": ["immobilier"],
  "remboursement-anticipe": ["immobilier"],
  "pret-taux-zero-ptz": ["ptz", "immobilier"],
  "pret-relais": ["immobilier"],
  "rachat-credit-immobilier": ["immobilier"],
  "assurance-emprunteur": ["immobilier"],
  "frais-agence-immobiliere": ["immobilier"],
  "frais-garantie-emprunt": ["immobilier"],
  "effort-epargne-immobilier": ["immobilier"],
  "impact-hausse-taux": ["immobilier"],
  "credit-travaux": ["immobilier"],
  "plus-value-immobiliere": ["fiscalite"],
  "rendement-locatif-brut": ["fiscalite"],
  "rendement-locatif-net": ["fiscalite"],
  "cash-flow-immobilier": ["fiscalite"],
  "rentabilite-lmnp": ["fiscalite"],
  "budget-travaux": ["immobilier"],
  "rentabilite-apres-travaux": ["immobilier"],
  "rentabilite-scpi": ["fiscalite"],
  "rentabilite-location-courte-duree": ["fiscalite"],
  "colocation-rentabilite": ["fiscalite"],
  "impot-revenus-fonciers": ["fiscalite", "impot"],
  "taxe-fonciere": ["fiscalite"],
  "deficit-foncier": ["fiscalite", "impot"],
  "donation-succession-immobiliere": ["donation"],
  "location-meublee-vs-nue": ["fiscalite"],
  "ifi-impot-fortune-immobiliere": ["ifi"],
  "revision-loyer-irl": ["immobilier"],
  "encadrement-loyers": ["immobilier"],
  "depot-garantie-locatif": ["immobilier"],
  "charges-recuperables-locataire": ["immobilier"],
  "revision-loyer-commercial": ["immobilier"],
  "loyer-charges-comprises": ["immobilier"],
  "mensualite-credit-consommation": ["fiscalite"],
  "interets-composes": ["retraite"],
  "simulateur-inflation": ["retraite"],
  "budget-reste-a-vivre": ["smic"],
  "simulateur-retraite": ["retraite"],
  "rendement-livret-a": ["retraite", "fiscalite"],
  "rendement-pea": ["fiscalite", "retraite"],
  "cout-total-credit-consommation": ["immobilier"],
  "loa-vs-credit-auto": ["immobilier"],
  "frais-kilometriques": ["fiscalite"],
  "salaire-brut-net": ["urssaf", "smic"],
  "salaire-net-brut": ["urssaf", "smic"],
  "cout-total-embauche-salarie": ["urssaf"],
  "indemnites-licenciement": ["urssaf", "smic"],
  "conges-payes-acquis": ["urssaf", "smic"],
  "ijss-arret-maladie": ["urssaf", "smic"],
  "allocation-chomage-are": ["urssaf", "smic"],
  "heures-supplementaires": ["urssaf", "smic"],
  "salaire-temps-partiel": ["urssaf", "smic"],
  "smic-net": ["smic", "urssaf"],
  "calculateur-tjm-freelance": ["immobilier", "fiscalite"],
  "revenu-net-independant": ["urssaf", "fiscalite"],
  "sasu-remuneration-dividendes": ["fiscalite", "impot"],
  "portage-salarial-vs-freelance": ["urssaf"],
  "seuil-franchise-tva": ["fiscalite"],
  "break-even-entreprise": ["fiscalite"],
  "marge-commerciale-taux": ["fiscalite"],
  "cout-horaire-charge-tns": ["immobilier", "urssaf"],
  "exoneration-acre": ["immobilier", "urssaf"],
  "facturation-objectif-revenu-net": ["urssaf", "fiscalite"],
  "impot-sur-le-revenu": ["impot"],
  "quotient-familial": ["impot"],
  "prelevement-a-la-source": ["impot"],
  "flat-tax-30-pourcent": ["fiscalite"],
  "micro-entrepreneur-charges": ["urssaf", "fiscalite"],
  "credit-impot-emploi-domicile": ["fiscalite"],
  "impot-dividendes": ["fiscalite", "impot"],
  "taux-marginal-imposition": ["impot"],
  "donation-numeraire": ["donation"],
  "cesu-credit-impot": ["fiscalite"],
  "quantite-peinture": ["immobilier"],
  "calcul-carrelage": ["immobilier"],
  "volume-beton": ["immobilier"],
  "surface-parquet": ["immobilier"],
  maprimerenov: ["immobilier"],
  "estimation-consommation-energie": ["immobilier"],
  "pompe-a-chaleur-economies": ["immobilier"],
  "volume-surface-piece": ["immobilier"],
  "quantite-mortier": ["immobilier"],
  "economies-isolation": ["immobilier"],
};

export function getSimulatorRegulationIds(slug: string): string[] | undefined {
  return SIMULATOR_REGULATION_IDS[slug];
}
